<#
Written by Ryan Ephgrave for ConfigMgr 2012 Right Click Tools
http://psrightclicktools.codeplex.com/
GUI Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
#>

$GetDirectory = $MyInvocation.MyCommand.path
$Directory = Split-Path $GetDirectory

function GenerateForm {

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$panel1 = New-Object System.Windows.Forms.Panel
$PSRightClickToolsLbl = New-Object System.Windows.Forms.Label
$Bylbl = New-Object System.Windows.Forms.Label
$VersionLbl = New-Object System.Windows.Forms.Label
$CloseBtn = New-Object System.Windows.Forms.Button
$AddRemoveBtn = New-Object System.Windows.Forms.Button
$linkLabel1 = New-Object System.Windows.Forms.LinkLabel
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.

$AddRemoveBtn_OnClick= 
{
	$ArgList = @()
	$ArgList += @("`"$Directory\SilentOpenPS.vbs`"")
	$ArgList += @("`"$Directory\Add Remove RC Tools.ps1`"")
	Start-Process wscript.exe -ArgumentList $ArgList
}

$Link_Clicked= 
{
	& start "http://psrightclicktools.codeplex.com"
}

$CloseBtn_OnClick= 
{
	$form1.Close()
}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 213
$System_Drawing_Size.Width = 457
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.FormBorderStyle = 1
$form1.MaximizeBox = $False
$form1.MinimizeBox = $False
$form1.Name = "form1"
$form1.Text = "About PowerShell Right Click Tools"


$panel1.BorderStyle = 1
$panel1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 12
$panel1.Location = $System_Drawing_Point
$panel1.Name = "panel1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 111
$System_Drawing_Size.Width = 433
$panel1.Size = $System_Drawing_Size
$panel1.TabIndex = 7

$form1.Controls.Add($panel1)
$PSRightClickToolsLbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 8
$System_Drawing_Point.Y = 11
$PSRightClickToolsLbl.Location = $System_Drawing_Point
$PSRightClickToolsLbl.Name = "PSRightClickToolsLbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 422
$PSRightClickToolsLbl.Size = $System_Drawing_Size
$PSRightClickToolsLbl.TabIndex = 0
$PSRightClickToolsLbl.Text = "PowerShell Right Click Tools"
$PSRightClickToolsLbl.TextAlign = 32

$panel1.Controls.Add($PSRightClickToolsLbl)

$Bylbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 8
$System_Drawing_Point.Y = 44
$Bylbl.Location = $System_Drawing_Point
$Bylbl.Name = "Bylbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 422
$Bylbl.Size = $System_Drawing_Size
$Bylbl.TabIndex = 1
$Bylbl.Text = "Written by Ryan Ephgrave for ConfigMgr 2012"
$Bylbl.TextAlign = 32

$panel1.Controls.Add($Bylbl)

$VersionLbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 8
$System_Drawing_Point.Y = 77
$VersionLbl.Location = $System_Drawing_Point
$VersionLbl.Name = "VersionLbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 422
$VersionLbl.Size = $System_Drawing_Size
$VersionLbl.TabIndex = 2
$VersionLbl.Text = "Version 1.4.0"
$VersionLbl.TextAlign = 32

$panel1.Controls.Add($VersionLbl)



$CloseBtn.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 361
$System_Drawing_Point.Y = 181
$CloseBtn.Location = $System_Drawing_Point
$CloseBtn.Name = "CloseBtn"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 84
$CloseBtn.Size = $System_Drawing_Size
$CloseBtn.TabIndex = 6
$CloseBtn.Text = "Close"
$CloseBtn.UseVisualStyleBackColor = $True
$CloseBtn.add_Click($CloseBtn_OnClick)

$form1.Controls.Add($CloseBtn)


$AddRemoveBtn.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 181
$AddRemoveBtn.Location = $System_Drawing_Point
$AddRemoveBtn.Name = "AddRemoveBtn"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 173
$AddRemoveBtn.Size = $System_Drawing_Size
$AddRemoveBtn.TabIndex = 4
$AddRemoveBtn.Text = "Add/Remove Tools"
$AddRemoveBtn.UseVisualStyleBackColor = $True
$AddRemoveBtn.add_Click($AddRemoveBtn_OnClick)

$form1.Controls.Add($AddRemoveBtn)

$linkLabel1.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 47
$System_Drawing_Point.Y = 135
$linkLabel1.Location = $System_Drawing_Point
$linkLabel1.Name = "linkLabel1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 366
$linkLabel1.Size = $System_Drawing_Size
$linkLabel1.TabIndex = 3
$linkLabel1.TabStop = $True
$linkLabel1.Text = "http://psrightclicktools.codeplex.com/"
$linkLabel1.TextAlign = 32
$linkLabel1.add_LinkClicked($Link_Clicked)

$form1.Controls.Add($linkLabel1)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
