<#
Written by Ryan Ephgrave for ConfigMgr 2012 Right Click Tools
http://myitforum.com/myitforumwp/author/ryan2065/
GUI Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
#>

$ResourceID = $args[0]
$Server = $args[1]
$Namespace = $args[2]

$strQuery = "Select ResourceID,ResourceNames from SMS_R_System where ResourceID='$ResourceID'"
Get-WmiObject -Query $strQuery -Namespace $Namespace -ComputerName $Server | ForEach-Object {$CompName = $_.ResourceNames[0]}


$GetDirectory = $MyInvocation.MyCommand.path
$Directory = Split-Path $GetDirectory

function GenerateForm {

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$StatusLbl = New-Object System.Windows.Forms.Label
$AboutBtn = New-Object System.Windows.Forms.Button
$RefreshBtn = New-Object System.Windows.Forms.Button
$TabControl = New-Object System.Windows.Forms.TabControl
$GenPage = New-Object System.Windows.Forms.TabPage
$CompInfoGrid = New-Object System.Windows.Forms.DataGridView
$CompInfoLbl = New-Object System.Windows.Forms.Label
$OSLbl = New-Object System.Windows.Forms.Label
$OSInfoGrid = New-Object System.Windows.Forms.DataGridView
$ProgTab = New-Object System.Windows.Forms.TabPage
$ReinstallBtn = New-Object System.Windows.Forms.Button
$UninstallBtn = New-Object System.Windows.Forms.Button
$AddRemoveLbl = New-Object System.Windows.Forms.Label
$AddRemoveGrid = New-Object System.Windows.Forms.DataGridView
$WinUpdateTab = New-Object System.Windows.Forms.TabPage
$WinUpdateView = New-Object System.Windows.Forms.DataGridView
$ExHist = New-Object System.Windows.Forms.TabPage
$ExHistGrid = New-Object System.Windows.Forms.DataGridView
$AppsTab = New-Object System.Windows.Forms.TabPage
$AppGridView = New-Object System.Windows.Forms.DataGridView
$ServicesTab = New-Object System.Windows.Forms.TabPage
$label5 = New-Object System.Windows.Forms.Label
$StartStopLbl = New-Object System.Windows.Forms.Label
$StartupTypeBox = New-Object System.Windows.Forms.ComboBox
$StartStopServBox = New-Object System.Windows.Forms.ComboBox
$ServicesGridView = New-Object System.Windows.Forms.DataGridView
$Drivers = New-Object System.Windows.Forms.TabPage
$DriverGrid = New-Object System.Windows.Forms.DataGridView
$CloseBtn = New-Object System.Windows.Forms.Button
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

$ReinstallBtn_OnClick= 
{
	$AddRemoveGrid.SelectedRows | ForEach-Object {$RowIndex = $_.index}
	$strSoftwareName = $AddRemoveGrid.Rows[$RowIndex].Cells[0].Value
	$strIDNumber = $AddRemoveGrid.Rows[$RowIndex].Cells[5].Value
	$Popup = New-Object -ComObject wscript.shell
	$msg = "Do you want to reinstall $strSoftwareName" + "?"
	$PopupAnswer = $Popup.popup($msg,0,"Are you sure?",1)
	if ($PopupAnswer -eq 1){
		$strQuery = "IdentifyingNumber='" + $strIDNumber + "'"
		$objUninstall = $null
		$objUninstall = Get-WmiObject -filter $strQuery -ComputerName $CompName -Class Win32_Product
		$Error.Clear()
		  if ($objUninstall -eq $null){$Popup.popup("Can not reinstall $strSoftwareName",0,"Error",0)}
		  else {$objUninstall.Reinstall(6)
		  if ($Error[0]){$Popup.Popup("Error when trying to reinstall $strSoftwareName",0,"Error",0)}
		  else {$Popup.Popup("Successfully triggered reinstall for $strSoftwareName",0,"Successful",0)}
		  }
	}
}

$RefreshBtn_OnClick= 
{
	$SelectedTab = $TabControl.SelectedTab.Text
	$SelectedTab = $SelectedTab | Out-String
	if ($SelectedTab.contains("General")) {
		$CompInfoGrid.rows.clear()
		$OSInfoGrid.rows.clear()
		$StatusLbl.Text = "Connecting to Win32_OperatingSystem on remote computer"
		$strQuery = "Select Caption,CSDVersion,InstallDate,LastBootUpTime from Win32_OperatingSystem"
		Get-WmiObject -Query $strQuery -Namespace root\cimv2 -ComputerName $CompName | ForEach-Object {
			[System.Windows.Forms.Application]::DoEvents()
			$OSInfoGrid.rows.add("Operating System",$_.Caption)
			$OSInfoGrid.rows.add("Service Pack",$_.CSDVersion)
			$OSInfoGrid.rows.add("Install Date",[Management.ManagementDateTimeConverter]::ToDateTime($_.InstallDate))
			$strBootTime = [Management.ManagementDateTimeConverter]::ToDateTime($_.LastBootUpTime)
		}
		$StatusLbl.Text = "Connecting to Win32_ComputerSystem on remote computer"
		$strQuery = "Select UserName,Domain,Model from Win32_ComputerSystem"
		Get-WmiObject -Query $strQuery -Namespace root\cimv2 -ComputerName $CompName | ForEach-Object {
			[System.Windows.Forms.Application]::DoEvents()
			$OSInfoGrid.rows.add("Domain",$_.Domain)
			$OSInfoGrid.rows.add("Console User",$_.UserName)
			$strModel = $_.Model
		}
		$OSInfoGrid.rows.add("Last Boot Time",$strBootTime)
		$StatusLbl.Text = "Connecting to Win32_BIOS on remote computer"
		$strQuery = "Select Manufacturer,SerialNumber,SMBIOSBIOSVersion,ReleaseDate from Win32_BIOS"
		Get-WmiObject -Query $strQuery -Namespace root\cimv2 -ComputerName $CompName | ForEach-Object {
			[System.Windows.Forms.Application]::DoEvents()
			$CompInfoGrid.rows.add("Manufacturer",$_.Manufacturer)
			$CompInfoGrid.rows.add("Model",$strModel)
			$CompInfoGrid.rows.add("Serial Number",$_.SerialNumber)
			$CompInfoGrid.rows.add("BIOS Version",$_.SMBIOSBIOSVersion)
			$CompInfoGrid.rows.add("BIOS Release Date",[Management.ManagementDateTimeConverter]::ToDateTime($_.ReleaseDate))
		}
		$NetAdapterCount = 0
		$StatusLbl.Text = "Connecting to Win32_NetworkAdapterConfiguration on remote computer"
		$strQuery = "select IPAddress,Description from Win32_NetworkAdapterConfiguration"
		Get-WmiObject -Query $strQuery -Namespace root\cimv2 -ComputerName $CompName | ForEach-Object {
			[System.Windows.Forms.Application]::DoEvents()
			$ArrayIP = $null
			$ArrayIP = $_.IPAddress
			if ($ArrayIP -ne $null) {
			$NetAdapterCount++
			$CompInfoGrid.rows.add("Network Adapter $NetAdapterCount",$_.Description)}
			foreach ($instance in $ArrayIP){
				if ($instance -ne $null){
					if ($instance.contains(".")){
						$CompInfoGrid.rows.add("IPv4 Address $NetAdapterCount",$instance)
					}
					elseif ($instance.contains(":")){
						$CompInfoGrid.rows.add("IPv6 Address $NetAdapterCount",$instance)
					}
				}
			}
		}
		$StatusLbl.Text = ""
	}
	elseif ($SelectedTab.contains("Programs")) {
		$AddRemoveGrid.rows.clear()
		$StatusLbl.Text = "Connecting to remote registry"
		$reg = [Microsoft.Win32.RegistryKey]::OpenRemoteBaseKey('LocalMachine', $CompName)
		$AddRemoveBranch = "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall"
		$AddRemoveKey = $reg.OpenSubKey($AddRemoveBranch)
		$StatusLbl.Text = "Gathering information"
		$AddRemoveKey.GetSubKeyNames() | ForEach-Object{
			[System.Windows.Forms.Application]::DoEvents()
			$IdentifyingNumber = $_
			$AddRemoveSubBranch = $AddRemoveBranch + "\\" + $_
			$AddRemoveSubKey = $reg.OpenSubKey($AddRemoveSubBranch)
			$strProgName = $AddRemoveSubKey.GetValue("DisplayName")
			if ($strProgName -ne $null) {
				$strPublisher = $AddRemoveSubKey.GetValue("Publisher")
				$strInstallDate = $AddRemoveSubKey.GetValue("InstallDate")
				$strVersion = $AddRemoveSubKey.GetValue("DisplayVersion")
				$strUninstallString = $AddRemoveSubKey.GetValue("UninstallString")
				$AddRemoveGrid.Rows.Add($strProgName,$strPublisher,$strInstallDate,$strVersion,$strUninstallString,$IdentifyingNumber)
			}
		}
		$StatusLbl.Text = ""
	}
	elseif ($SelectedTab.Contains("Execution")) {
		$ExHistGrid.rows.clear()
		$StatusLbl.Text = "Connecting to remote registry"
		$reg = [Microsoft.Win32.RegistryKey]::OpenRemoteBaseKey('LocalMachine', $CompName)
		$ExHistBranch = "SOFTWARE\\Microsoft\\SMS\\Mobile Client\\Software Distribution\\Execution History"
		$ExHistKey = $reg.OpenSubKey($ExHistBranch)
		$StatusLbl.Text = "Gathering information"
		$ExHistKey.GetSubKeyNames() | ForEach-Object{
			[System.Windows.Forms.Application]::DoEvents()
			$strUser = $_
			$UserSubKeyBranch = $ExHistBranch + "\\" + $_
			$UserSubKey = $reg.OpenSubKey($UserSubKeyBranch)
			$UserSubKeyNames = $UserSubKey.GetSubKeyNames()
			foreach ($ProgIDKey in $UserSubKeyNames){
				$strPackageID = $ProgIDKey
				$ProgIDBranch = $UserSubKeyBranch + "\\" + $ProgIDKey
				$ProgIDKey = $reg.OpenSubKey($ProgIDBranch)
				$ProgIDKeyNames = $ProgIDKey.GetSubKeyNames()
				foreach ($ProgSchedID in $ProgIDKeyNames) {
					$ProgSchedIDBranch = $ProgIDBranch + "\\" + $ProgSchedID
					$ProgSchedIDKey = $reg.OpenSubKey($ProgSchedIDBranch)
					$strState = $ProgSchedIDKey.GetValue("_State")
					$strProgName = $ProgSchedIDKey.GetValue("_ProgramID")
					$strStartTime = $ProgSchedIDKey.GetValue("_RunStartTime")
					$strErrorCode = $ProgSchedIDKey.GetValue("SuccessOrFailureCode")
					$strErrorMsg = $ProgSchedIDKey.GetValue("SuccessOrFailureReason")
					$ExHistGrid.Rows.Add($strState,$strUser,$strPackageID,$strProgName,$strStartTime,$strErrorCode,$strErrorMsg)
				}
			}
		}
		$StatusLbl.Text = ""
	}
	elseif ($SelectedTab.Contains("Applicatio")) {
		$AppGridView.rows.clear()
		$FoundApps = $false
		$StatusLbl.Text = "Connecting to CCM_Application on remote computer"
		$strQuery = "select * from CCM_Application"
		Get-WmiObject -Query $strQuery -Namespace root\ccm\clientsdk -ComputerName $CompName | ForEach-Object {
			[System.Windows.Forms.Application]::DoEvents()
			$SoftwareName = $_.Name
			if ($SoftwareName -ne $null) {$FoundApps = $true}
			$SoftwareVersion = $_.SoftwareVersion
			$InstallState = $_.InstallState
			$EvalTime = $_.ConvertToDateTime($_.LastEvalTime)
			$EvalTime = $EvalTime.ToShortDateString() + " " + $EvalTime.ToShortTimeString()
			$IsMachineTarget = $_.IsMachineTarget
			$Deadline = $_.ConvertToDateTime($_.Deadline)
			$Deadline = $Deadline.ToShortDateString() + " " + $Deadline.ToShortTimeString()
			$AppGridView.rows.add($SoftwareName,$SoftwareVersion,$InstallState,$EvalTime,$IsMachineTarget,$Deadline)
		}
		if ($FoundApps -eq $false) {
			$AppGridView.rows.add("Found no apps deployed to machine")
		}
		$StatusLbl.Text = ""
	}
	elseif ($SelectedTab.Contains("Service")) {
		$ServicesGridView.rows.clear()
		$StatusLbl.Text = "Connecting to Win32_Service on remote computer"
		Get-WmiObject -Class Win32_Service -Namespace root\cimv2 -ComputerName $CompName | ForEach-Object {
			[System.Windows.Forms.Application]::DoEvents()
			$strStartMode = $_.StartMode
			$strServiceName = $_.Name
			if ($strStartMode -eq "Auto"){
				$ServiceBranch = "System\\CurrentControlSet\\Services\\$strServiceName"
				$ServiceSubKey = $reg.OpenSubKey($ServiceBranch)
				$AutoStartType = $null
				$AutoStartType = $ServiceSubKey.GetValue("DelayedAutostart")
				if ($AutoStartType -eq "1") {$strStartMode = "Automatic (Delayed Start)"}
				else {$strStartMode = "Automatic"}
			}
		$ServicesGridView.rows.add($_.DisplayName,$_.Name,$_.State,$strStartMode,$_.Description)
		}
		$StatusLbl.Text = ""
	}
	elseif ($SelectedTab.Contains("Update")) {
		$WinUpdateView.Rows.Clear()
		$StatusLbl.Text = "Connecting to WMI - Win32_QuickFixEngineering"
		$strQuery = "Select Caption,Description,HotFixID,InstalledBy,InstalledOn from Win32_QuickFixEngineering"
		Get-WmiObject -Query $strQuery -Namespace root\cimv2 -ComputerName $CompName | ForEach-Object {
			$WinUpdateView.Rows.Add($_.HotFixID,$_.Description,$_.InstalledOn,$_.InstalledBy,$_.Caption)
		}
	}
	elseif ($SelectedTab.Contains("Driver")) {
		$DriverGrid.Rows.Clear()
		$StatusLbl.Text = "Connecting to Win32_PnPSignedDriver"
		$strQuery = "Select DeviceName,DeviceClass,DeviceID,DriverDate,IsSigned,DriverVersion from Win32_PnPSignedDriver"
		Get-WmiObject -Query $strQuery -Namespace root\cimv2 -ComputerName $CompName | ForEach-Object {
			$DriverGrid.Rows.Add($_.DeviceName,$_.DeviceClass,[Management.ManagementDateTimeConverter]::ToDateTime($_.DriverDate),$_.DriverVersion,$_.IsSigned,$_.DeviceID)
		}
	}
	$StatusLbl.Text = ""
}

$AboutBtn_OnClick= 
{
	$ArgList = @()
	$ArgList += @("`"$Directory\SilentOpenPS.vbs`"")
	$ArgList += @("`"$Directory\About.ps1`"")
	Start-Process wscript.exe -ArgumentList $ArgList
}

$UninstallBtn_OnClick= 
{
	$AddRemoveGrid.SelectedRows | ForEach-Object {$RowIndex = $_.index}
	$strSoftwareName = $AddRemoveGrid.Rows[$RowIndex].Cells[0].Value
	$strIDNumber = $AddRemoveGrid.Rows[$RowIndex].Cells[5].Value
	$Popup = New-Object -ComObject wscript.shell
	$msg = "Do you want to uninstall $strSoftwareName" + "?"
	$PopupAnswer = $Popup.popup($msg,0,"Are you sure?",1)
	if ($PopupAnswer -eq 1){
		$strQuery = "IdentifyingNumber='" + $strIDNumber + "'"
		 $objUninstall = $null
		 $objUninstall = Get-WmiObject -filter $strQuery -ComputerName $CompName -Class Win32_Product
		 $Error.Clear()
		  if ($objUninstall -eq $null){$Popup.popup("Could not uninstall $strSoftwareName",0,"Error",0)}
		  else {$objUninstall.Uninstall()
		  if ($Error[0]){$Popup.Popup("Error when trying to uninstall $strSoftwareName",0,"Error",0)}
		  else {$Popup.Popup("Successfully triggered uninstall for $strSoftwareName",0,"Successful",0)}
		  }
	}
}

$CloseBtn_OnClick= 
{
	$ProcessID = [System.Diagnostics.Process]::GetCurrentProcess()
	$ProcID = $ProcessID.ID
	& taskkill /PID $ProcID /T /F
}


$StartStopServBox_OnChange = 
{
	$CanDoSomething = 0
	$StartStopServAction = $StartStopServBox.SelectedItem
	$ServicesGridView.SelectedRows | ForEach-Object {$RowIndex = $_.index}
	$strServiceName = $ServicesGridView.Rows[$RowIndex].Cells[1].Value
	$strCurrentStatus = $ServicesGridView.Rows[$RowIndex].Cells[2].Value
	if ($StartStopServAction -eq "Start") {if ($strCurrentStatus -eq "Stopped") {$CanDoSomething = 1}}
	elseif ($StartStopServAction -eq "Resume") {if ($strCurrentStatus -eq "Paused") {$CanDoSomething = 1}}
	elseif ($StartStopServAction -eq "Stop"){if ($strCurrentStatus -eq "Running") {$CanDoSomething = 1}}
	elseif ($StartStopServAction -eq "Pause") {if ($strCurrentStatus -eq "Running") {$CanDoSomething = 1}}
	if ($CanDoSomething -eq 1){
		$Popup = New-Object -ComObject wscript.shell
		$msg = "Do you want to $StartStopServAction $strServiceName"
		$PopupAnswer = $Popup.popup($msg,0,"Are you sure?",1)
		if ($PopupAnswer -eq 1){
			$Error.Clear()
			if ($StartStopServAction -eq "Start") {
				$strQuery = "Select * from Win32_Service where Name='" + $strServiceName + "'"
				Get-WmiObject -Query $strQuery -Namespace root\cimv2 -ComputerName $CompName | ForEach-Object {$CheckError = $_.StartService()}
			}
			elseif ($StartStopServAction -eq "Resume") {
				$strQuery = "Select * from Win32_Service where Name='" + $strServiceName + "'"
				Get-WmiObject -Query $strQuery -Namespace root\cimv2 -ComputerName $CompName | ForEach-Object {$CheckError = $_.ResumeService()}
			}
			elseif ($StartStopServAction -eq "Stop"){
				$strQuery = "Select * from Win32_Service where Name='" + $strServiceName + "'"
				Get-WmiObject -Query $strQuery -Namespace root\cimv2 -ComputerName $CompName | ForEach-Object {$CheckError = $_.StopService()}
			}
			elseif ($StartStopServAction -eq "Pause") {
				$strQuery = "Select * from Win32_Service where Name='" + $strServiceName + "'"
				Get-WmiObject -Query $strQuery -Namespace root\cimv2 -ComputerName $CompName | ForEach-Object {$CheckError = $_.PauseService()}
			}
			if ($Error[0] -or $CheckError.ReturnValue -ne 0) {
				$strError = $CheckError.ReturnValue
				if ($strError -eq 1){$strErrorDescription = "Not Supported"}
				elseif ($strError -eq 2){$strErrorDescription = "Access Denied"}
				elseif ($strError -eq 3){$strErrorDescription = "Dependent Services Running"}
				elseif ($strError -eq 4){$strErrorDescription = "Invalid Service Control"}
				elseif ($strError -eq 5){$strErrorDescription = "Service Cannot Accept Control"}
				elseif ($strError -eq 6){$strErrorDescription = "Service Not Active"}
				elseif ($strError -eq 7){$strErrorDescription = "Service Request Timeout"}
				elseif ($strError -eq 8){$strErrorDescription = "Unknown Failure"}
				elseif ($strError -eq 9){$strErrorDescription = "Path Not Found"}
				elseif ($strError -eq 10){$strErrorDescription = "Service Already Running"}
				elseif ($strError -eq 11){$strErrorDescription = "Service Database Locked"}
				elseif ($strError -eq 12){$strErrorDescription = "Service Dependency Deleted"}
				elseif ($strError -eq 13){$strErrorDescription = "Service Dependency Failure"}
				elseif ($strError -eq 14){$strErrorDescription = "Service Disabled"}
				elseif ($strError -eq 15){$strErrorDescription = "Service Logon Failure"}
				elseif ($strError -eq 16){$strErrorDescription = "Service Marked For Deletion"}
				elseif ($strError -eq 17){$strErrorDescription = "Service No Thread"}
				elseif ($strError -eq 18){$strErrorDescription = "Status Circular Dependency"}
				elseif ($strError -eq 19){$strErrorDescription = "Status Duplicate Name"}
				elseif ($strError -eq 20){$strErrorDescription = "Status Invalid Name"}
				elseif ($strError -eq 21){$strErrorDescription = "Status Invalid Parameter"}
				elseif ($strError -eq 22){$strErrorDescription = "Status Invalid Service Account"}
				elseif ($strError -eq 23){$strErrorDescription = "Status Service Exists"}
				elseif ($strError -eq 24){$strErrorDescription = "Service Already Paused"}
				else{$strErrorDescription = "Unknown Error"}
				$Popup.popup("Error changing $strServiceName startup type.  Error code $strError  Error Reason: $strErrorDescription",0,"Error",0)
			}
			else {
				$Popup.popup("Successfully changed $strServiceName state",0,"Successful",0)
			}
		}
	}
}

$StartupTypeBox_OnChange = 
{
	$CheckError = $null
	$ServicesGridView.SelectedRows | ForEach-Object {$RowIndex = $_.index}
	$strServiceName = $ServicesGridView.Rows[$RowIndex].Cells[1].Value
	$strCurrentStartupType = $ServicesGridView.Rows[$RowIndex].Cells[3].Value
	if ($strCurrentStartupType -eq "Automatic (Delayed Start)") {$strCurrentStartupType = "Automatic"}
	$strNewStartupType = $StartupTypeBox.SelectedItem
	if ($strNewStartupType -ne $strCurrentStartupType){
		$Popup = New-Object -ComObject wscript.shell
		$msg = "Do you want to make the startup of $strServiceName $strNewStartupType"
		$PopupAnswer = $Popup.popup($msg,0,"Are you sure?",1)
		if ($PopupAnswer -eq 1){
			$Error.Clear()
			if ($strNewStartupType -eq "Automatic"){
				$strQuery = "Select * from Win32_Service where Name='" + $strServiceName + "'"
				Get-WmiObject -Query $strQuery -Namespace root\cimv2 -ComputerName $CompName | ForEach-Object {$CheckError = $_.ChangeStartMode($strNewStartupType)}
				if ($CheckError.ReturnValue -eq 0) {
					$strKeyLocation = "\\" + $CompName + "\HKLM\SYSTEM\CurrentControlSet\services\$strServiceName"
					& reg add $strKeyLocation /v DelayedAutoStart /t REG_DWORD /d 0 /f
				}
			}
			elseif ($strNewStartupType -eq "Manual") {
				$strQuery = "Select * from Win32_Service where Name='" + $strServiceName + "'"
				Get-WmiObject -Query $strQuery -Namespace root\cimv2 -ComputerName $CompName | ForEach-Object {$CheckError = $_.ChangeStartMode($strNewStartupType)}
			}
			elseif ($strNewStartupType -eq "Disabled") {
				$strQuery = "Select * from Win32_Service where Name='" + $strServiceName + "'"
				Get-WmiObject -Query $strQuery -Namespace root\cimv2 -ComputerName $CompName | ForEach-Object {$CheckError = $_.ChangeStartMode($strNewStartupType)}
			}
			if ($Error[0] -or $CheckError.ReturnValue -ne 0) {
				$strError = $CheckError.ReturnValue
				if ($strError -eq 1){$strErrorDescription = "Not Supported"}
				elseif ($strError -eq 2){$strErrorDescription = "Access Denied"}
				elseif ($strError -eq 3){$strErrorDescription = "Dependent Services Running"}
				elseif ($strError -eq 4){$strErrorDescription = "Invalid Service Control"}
				elseif ($strError -eq 5){$strErrorDescription = "Service Cannot Accept Control"}
				elseif ($strError -eq 6){$strErrorDescription = "Service Not Active"}
				elseif ($strError -eq 7){$strErrorDescription = "Service Request Timeout"}
				elseif ($strError -eq 8){$strErrorDescription = "Unknown Failure"}
				elseif ($strError -eq 9){$strErrorDescription = "Path Not Found"}
				elseif ($strError -eq 10){$strErrorDescription = "Service Already Running"}
				elseif ($strError -eq 11){$strErrorDescription = "Service Database Locked"}
				elseif ($strError -eq 12){$strErrorDescription = "Service Dependency Deleted"}
				elseif ($strError -eq 13){$strErrorDescription = "Service Dependency Failure"}
				elseif ($strError -eq 14){$strErrorDescription = "Service Disabled"}
				elseif ($strError -eq 15){$strErrorDescription = "Service Logon Failure"}
				elseif ($strError -eq 16){$strErrorDescription = "Service Marked For Deletion"}
				elseif ($strError -eq 17){$strErrorDescription = "Service No Thread"}
				elseif ($strError -eq 18){$strErrorDescription = "Status Circular Dependency"}
				elseif ($strError -eq 19){$strErrorDescription = "Status Duplicate Name"}
				elseif ($strError -eq 20){$strErrorDescription = "Status Invalid Name"}
				elseif ($strError -eq 21){$strErrorDescription = "Status Invalid Parameter"}
				elseif ($strError -eq 22){$strErrorDescription = "Status Invalid Service Account"}
				elseif ($strError -eq 23){$strErrorDescription = "Status Service Exists"}
				elseif ($strError -eq 24){$strErrorDescription = "Service Already Paused"}
				else{$strErrorDescription = "Unknown Error"}
				$Popup.popup("Error changing $strServiceName startup type.  Error code $strError  Error Reason: $strErrorDescription",0,"Error",0)
			}
			else {
				$Popup.popup("Successfully changed $strServiceName startup type",0,"Successful",0)
			}
		}
	}
}

$ServicesGridView_OnClick = 
{
	$ServicesGridView.SelectedRows | ForEach-Object {$RowIndex = $_.index}
	$strStartType = $ServicesGridView.Rows[$RowIndex].Cells[3].Value
	if ($strStartType -eq "Automatic (Delayed Start)"){$strStartType = "Automatic"}
	$StartupTypeBox.SelectedItem = $strStartType
}

$ResizeEnd=
{
	$FormHeight = $form1.Size.Height
	$DataGridHeight = $FormHeight - 168
	$DataGridheight = $DataGridHeight / 2
	$System_Drawing_Size.Width = $OSInfoGrid.Size.Width
	$System_Drawing_Size.Height = $DataGridHeight - 7
	$OSInfoGrid.Size = $System_Drawing_Size
	$System_Drawing_Size.Width = $OSInfoGrid.Size.Width
	$System_Drawing_Size.Height = $DataGridHeight
	$CompInfoGrid.Size = $System_Drawing_Size
	$System_Drawing_Point.X = 3
	$System_Drawing_Point.Y = 28
	$OSInfoGrid.Location = $System_Drawing_Point
}

$TabControl_OnSelected=
{
	$SelectedTab = $TabControl.SelectedTab.Text
	$SelectedTab = $SelectedTab | Out-String
	if ($SelectedTab.contains("General")) {
		$CompInfoGrid.rows.clear()
		$OSInfoGrid.rows.clear()
		$StatusLbl.Text = "Connecting to Win32_OperatingSystem on remote computer"
		$strQuery = "Select Caption,CSDVersion,InstallDate,LastBootUpTime from Win32_OperatingSystem"
		Get-WmiObject -Query $strQuery -Namespace root\cimv2 -ComputerName $CompName | ForEach-Object {
			[System.Windows.Forms.Application]::DoEvents()
			$OSInfoGrid.rows.add("Operating System",$_.Caption)
			$OSInfoGrid.rows.add("Service Pack",$_.CSDVersion)
			$OSInfoGrid.rows.add("Install Date",[Management.ManagementDateTimeConverter]::ToDateTime($_.InstallDate))
			$strBootTime = [Management.ManagementDateTimeConverter]::ToDateTime($_.LastBootUpTime)
		}
		$StatusLbl.Text = "Connecting to Win32_ComputerSystem on remote computer"
		$strQuery = "Select UserName,Domain,Model from Win32_ComputerSystem"
		Get-WmiObject -Query $strQuery -Namespace root\cimv2 -ComputerName $CompName | ForEach-Object {
			[System.Windows.Forms.Application]::DoEvents()
			$OSInfoGrid.rows.add("Domain",$_.Domain)
			$OSInfoGrid.rows.add("Console User",$_.UserName)
			$strModel = $_.Model
		}
		$OSInfoGrid.rows.add("Last Boot Time",$strBootTime)
		$StatusLbl.Text = "Connecting to Win32_BIOS on remote computer"
		$strQuery = "Select Manufacturer,SerialNumber,SMBIOSBIOSVersion,ReleaseDate from Win32_BIOS"
		Get-WmiObject -Query $strQuery -Namespace root\cimv2 -ComputerName $CompName | ForEach-Object {
			[System.Windows.Forms.Application]::DoEvents()
			$CompInfoGrid.rows.add("Manufacturer",$_.Manufacturer)
			$CompInfoGrid.rows.add("Model",$strModel)
			$CompInfoGrid.rows.add("Serial Number",$_.SerialNumber)
			$CompInfoGrid.rows.add("BIOS Version",$_.SMBIOSBIOSVersion)
			$CompInfoGrid.rows.add("BIOS Release Date",[Management.ManagementDateTimeConverter]::ToDateTime($_.ReleaseDate))
		}
		$NetAdapterCount = 0
		$StatusLbl.Text = "Connecting to Win32_NetworkAdapterConfiguration on remote computer"
		$strQuery = "select IPAddress,Description from Win32_NetworkAdapterConfiguration"
		Get-WmiObject -Query $strQuery -Namespace root\cimv2 -ComputerName $CompName | ForEach-Object {
			[System.Windows.Forms.Application]::DoEvents()
			$ArrayIP = $null
			$ArrayIP = $_.IPAddress
			if ($ArrayIP -ne $null) {
			$NetAdapterCount++
			$CompInfoGrid.rows.add("Network Adapter $NetAdapterCount",$_.Description)}
			foreach ($instance in $ArrayIP){
				if ($instance -ne $null){
					if ($instance.contains(".")){
						$CompInfoGrid.rows.add("IPv4 Address $NetAdapterCount",$instance)
					}
					elseif ($instance.contains(":")){
						$CompInfoGrid.rows.add("IPv6 Address $NetAdapterCount",$instance)
					}
				}
			}
		}
		$StatusLbl.Text = ""
	}
	elseif ($SelectedTab.contains("Programs")) {
		$AddRemoveGrid.rows.clear()
		$StatusLbl.Text = "Connecting to remote registry"
		$reg = [Microsoft.Win32.RegistryKey]::OpenRemoteBaseKey('LocalMachine', $CompName)
		$AddRemoveBranch = "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall"
		$AddRemoveKey = $reg.OpenSubKey($AddRemoveBranch)
		$StatusLbl.Text = "Gathering information"
		$AddRemoveKey.GetSubKeyNames() | ForEach-Object{
			[System.Windows.Forms.Application]::DoEvents()
			$IdentifyingNumber = $_
			$AddRemoveSubBranch = $AddRemoveBranch + "\\" + $_
			$AddRemoveSubKey = $reg.OpenSubKey($AddRemoveSubBranch)
			$strProgName = $AddRemoveSubKey.GetValue("DisplayName")
			if ($strProgName -ne $null) {
				$strPublisher = $AddRemoveSubKey.GetValue("Publisher")
				$strInstallDate = $AddRemoveSubKey.GetValue("InstallDate")
				$strVersion = $AddRemoveSubKey.GetValue("DisplayVersion")
				$strUninstallString = $AddRemoveSubKey.GetValue("UninstallString")
				$AddRemoveGrid.Rows.Add($strProgName,$strPublisher,$strInstallDate,$strVersion,$strUninstallString,$IdentifyingNumber)
			}
		}
		$StatusLbl.Text = ""
	}
	elseif ($SelectedTab.Contains("Execution")) {
		$ExHistGrid.rows.clear()
		$StatusLbl.Text = "Connecting to remote registry"
		$reg = [Microsoft.Win32.RegistryKey]::OpenRemoteBaseKey('LocalMachine', $CompName)
		$ExHistBranch = "SOFTWARE\\Microsoft\\SMS\\Mobile Client\\Software Distribution\\Execution History"
		$ExHistKey = $reg.OpenSubKey($ExHistBranch)
		$StatusLbl.Text = "Gathering information"
		$ExHistKey.GetSubKeyNames() | ForEach-Object{
			[System.Windows.Forms.Application]::DoEvents()
			$strUser = $_
			$UserSubKeyBranch = $ExHistBranch + "\\" + $_
			$UserSubKey = $reg.OpenSubKey($UserSubKeyBranch)
			$UserSubKeyNames = $UserSubKey.GetSubKeyNames()
			foreach ($ProgIDKey in $UserSubKeyNames){
				$strPackageID = $ProgIDKey
				$ProgIDBranch = $UserSubKeyBranch + "\\" + $ProgIDKey
				$ProgIDKey = $reg.OpenSubKey($ProgIDBranch)
				$ProgIDKeyNames = $ProgIDKey.GetSubKeyNames()
				foreach ($ProgSchedID in $ProgIDKeyNames) {
					$ProgSchedIDBranch = $ProgIDBranch + "\\" + $ProgSchedID
					$ProgSchedIDKey = $reg.OpenSubKey($ProgSchedIDBranch)
					$strState = $ProgSchedIDKey.GetValue("_State")
					$strProgName = $ProgSchedIDKey.GetValue("_ProgramID")
					$strStartTime = $ProgSchedIDKey.GetValue("_RunStartTime")
					$strErrorCode = $ProgSchedIDKey.GetValue("SuccessOrFailureCode")
					$strErrorMsg = $ProgSchedIDKey.GetValue("SuccessOrFailureReason")
					$ExHistGrid.Rows.Add($strState,$strUser,$strPackageID,$strProgName,$strStartTime,$strErrorCode,$strErrorMsg)
				}
			}
		}
		$StatusLbl.Text = ""
	}
	elseif ($SelectedTab.Contains("Applicatio")) {
		$AppGridView.rows.clear()
		$FoundApps = $false
		$StatusLbl.Text = "Connecting to CCM_Application on remote computer"
		$strQuery = "select * from CCM_Application"
		Get-WmiObject -Query $strQuery -Namespace root\ccm\clientsdk -ComputerName $CompName | ForEach-Object {
			[System.Windows.Forms.Application]::DoEvents()
			$SoftwareName = $_.Name
			if ($SoftwareName -ne $null) {$FoundApps = $true}
			$SoftwareVersion = $_.SoftwareVersion
			$InstallState = $_.InstallState
			$EvalTime = $_.ConvertToDateTime($_.LastEvalTime)
			$EvalTime = $EvalTime.ToShortDateString() + " " + $EvalTime.ToShortTimeString()
			$IsMachineTarget = $_.IsMachineTarget
			$Deadline = $_.ConvertToDateTime($_.Deadline)
			$Deadline = $Deadline.ToShortDateString() + " " + $Deadline.ToShortTimeString()
			$AppGridView.rows.add($SoftwareName,$SoftwareVersion,$InstallState,$EvalTime,$IsMachineTarget,$Deadline)
		}
		if ($FoundApps -eq $false) {
			$AppGridView.rows.add("Found no apps deployed to machine")
		}
		$StatusLbl.Text = ""
	}
	elseif ($SelectedTab.Contains("Service")) {
		$ServicesGridView.rows.clear()
		$StatusLbl.Text = "Connecting to Win32_Service on remote computer"
		Get-WmiObject -Class Win32_Service -Namespace root\cimv2 -ComputerName $CompName | ForEach-Object {
			[System.Windows.Forms.Application]::DoEvents()
			$strStartMode = $_.StartMode
			$strServiceName = $_.Name
			if ($strStartMode -eq "Auto"){
				$ServiceBranch = "System\\CurrentControlSet\\Services\\$strServiceName"
				$ServiceSubKey = $reg.OpenSubKey($ServiceBranch)
				$AutoStartType = $null
				$AutoStartType = $ServiceSubKey.GetValue("DelayedAutostart")
				if ($AutoStartType -eq "1") {$strStartMode = "Automatic (Delayed Start)"}
				else {$strStartMode = "Automatic"}
			}
		$ServicesGridView.rows.add($_.DisplayName,$_.Name,$_.State,$strStartMode,$_.Description)
		}
		$StatusLbl.Text = ""
	}
	elseif ($SelectedTab.Contains("Update")) {
		$WinUpdateView.Rows.Clear()
		$StatusLbl.Text = "Connecting to WMI - Win32_QuickFixEngineering"
		$strQuery = "Select Caption,Description,HotFixID,InstalledBy,InstalledOn from Win32_QuickFixEngineering"
		Get-WmiObject -Query $strQuery -Namespace root\cimv2 -ComputerName $CompName | ForEach-Object {
			$WinUpdateView.Rows.Add($_.HotFixID,$_.Description,$_.InstalledOn,$_.InstalledBy,$_.Caption)
		}
	}
	elseif ($SelectedTab.Contains("Driver")) {
		$DriverGrid.Rows.Clear()
		$StatusLbl.Text = "Connecting to Win32_PnPSignedDriver"
		$strQuery = "Select DeviceName,DeviceClass,DeviceID,DriverDate,IsSigned,DriverVersion from Win32_PnPSignedDriver"
		Get-WmiObject -Query $strQuery -Namespace root\cimv2 -ComputerName $CompName | ForEach-Object {
			$DriverGrid.Rows.Add($_.DeviceName,$_.DeviceClass,[Management.ManagementDateTimeConverter]::ToDateTime($_.DriverDate),$_.DriverVersion,$_.IsSigned,$_.DeviceID)
		}
	}
	$StatusLbl.Text = ""
}

$OnLoadForm_StateCorrection=
{
	$form1.WindowState = $InitialFormWindowState
	if (Test-Connection -ComputerName $CompName -Count 1 -Quiet){
		$strQuery = "Select Caption,CSDVersion,InstallDate,LastBootUpTime from Win32_OperatingSystem"
		Get-WmiObject -Query $strQuery -Namespace root\cimv2 -ComputerName $CompName | ForEach-Object {
			[System.Windows.Forms.Application]::DoEvents()
			$OSInfoGrid.rows.add("Operating System",$_.Caption)
			$OSInfoGrid.rows.add("Service Pack",$_.CSDVersion)
			$OSInfoGrid.rows.add("Install Date",[Management.ManagementDateTimeConverter]::ToDateTime($_.InstallDate))
			$strBootTime = [Management.ManagementDateTimeConverter]::ToDateTime($_.LastBootUpTime)
		}
		$strQuery = "Select UserName,Domain,Model from Win32_ComputerSystem"
		Get-WmiObject -Query $strQuery -Namespace root\cimv2 -ComputerName $CompName | ForEach-Object {
			[System.Windows.Forms.Application]::DoEvents()
			$OSInfoGrid.rows.add("Domain",$_.Domain)
			$OSInfoGrid.rows.add("Console User",$_.UserName)
			$strModel = $_.Model
		}
		$OSInfoGrid.rows.add("Last Boot Time",$strBootTime)
		$strQuery = "Select Manufacturer,SerialNumber,SMBIOSBIOSVersion,ReleaseDate from Win32_BIOS"
		Get-WmiObject -Query $strQuery -Namespace root\cimv2 -ComputerName $CompName | ForEach-Object {
			[System.Windows.Forms.Application]::DoEvents()
			$CompInfoGrid.rows.add("Manufacturer",$_.Manufacturer)
			$CompInfoGrid.rows.add("Model",$strModel)
			$CompInfoGrid.rows.add("Serial Number",$_.SerialNumber)
			$CompInfoGrid.rows.add("BIOS Version",$_.SMBIOSBIOSVersion)
			$CompInfoGrid.rows.add("BIOS Release Date",[Management.ManagementDateTimeConverter]::ToDateTime($_.ReleaseDate))
		}
		$NetAdapterCount = 0
		$strQuery = "select IPAddress,Description from Win32_NetworkAdapterConfiguration"
		Get-WmiObject -Query $strQuery -Namespace root\cimv2 -ComputerName $CompName | ForEach-Object {
			[System.Windows.Forms.Application]::DoEvents()
			$ArrayIP = $null
			$ArrayIP = $_.IPAddress
			if ($ArrayIP -ne $null) {
				$NetAdapterCount++
				$CompInfoGrid.rows.add("Network Adapter $NetAdapterCount",$_.Description)
			}
			foreach ($instance in $ArrayIP){
				if ($instance -ne $null){
					if ($instance.contains(".")){
						$CompInfoGrid.rows.add("IPv4 Address $NetAdapterCount",$instance)
					}
				elseif ($instance.contains(":")){$CompInfoGrid.rows.add("IPv6 Address $NetAdapterCount",$instance)}
				}
			}
		}
	}
	else {
		$Popup = New-Object -ComObject wscript.shell
		$msg = "Could not ping $CompName"
		$PopupAnswer = $Popup.popup($msg,0,"Error",0)
		$ProcessID = [System.Diagnostics.Process]::GetCurrentProcess()
		$ProcID = $ProcessID.ID
		& taskkill /PID $ProcID /T /F
	}
}

#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 439
$System_Drawing_Size.Width = 835
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.MaximizeBox = $true
$form1.Name = "form1"
$form1.Text = "System Information - $CompName"

$StatusLbl.Anchor = 14
$StatusLbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 142
$System_Drawing_Point.Y = 409
$StatusLbl.Location = $System_Drawing_Point
$StatusLbl.Name = "StatusLbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 462
$StatusLbl.Size = $System_Drawing_Size
$StatusLbl.TabIndex = 7
$StatusLbl.TextAlign = 16

$form1.Controls.Add($StatusLbl)

$AboutBtn.Anchor = 6

$AboutBtn.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 19
$System_Drawing_Point.Y = 409
$AboutBtn.Location = $System_Drawing_Point
$AboutBtn.Name = "AboutBtn"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$AboutBtn.Size = $System_Drawing_Size
$AboutBtn.TabIndex = 6
$AboutBtn.Text = "About"
$AboutBtn.UseVisualStyleBackColor = $True
$AboutBtn.add_Click($AboutBtn_OnClick)

$form1.Controls.Add($AboutBtn)

$RefreshBtn.Anchor = 10

$RefreshBtn.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 634
$System_Drawing_Point.Y = 409
$RefreshBtn.Location = $System_Drawing_Point
$RefreshBtn.Name = "RefreshBtn"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$RefreshBtn.Size = $System_Drawing_Size
$RefreshBtn.TabIndex = 2
$RefreshBtn.Text = "Refresh"
$RefreshBtn.UseVisualStyleBackColor = $True
$RefreshBtn.add_Click($RefreshBtn_OnClick)

$form1.Controls.Add($RefreshBtn)

$TabControl.Anchor = 15
$TabControl.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 12
$TabControl.Location = $System_Drawing_Point
$TabControl.Name = "TabControl"
$TabControl.SelectedIndex = 0
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 391
$System_Drawing_Size.Width = 819
$TabControl.Size = $System_Drawing_Size
$TabControl.TabIndex = 5
$TabControl.add_Selected($TabControl_OnSelected)

$form1.Controls.Add($TabControl)
$GenPage.BackColor = [System.Drawing.Color]::FromArgb(0,255,255,255)
$GenPage.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 22
$GenPage.Location = $System_Drawing_Point
$GenPage.Name = "GenPage"
$System_Windows_Forms_Padding = New-Object System.Windows.Forms.Padding
$System_Windows_Forms_Padding.All = 3
$System_Windows_Forms_Padding.Bottom = 3
$System_Windows_Forms_Padding.Left = 3
$System_Windows_Forms_Padding.Right = 3
$System_Windows_Forms_Padding.Top = 3
$GenPage.Padding = $System_Windows_Forms_Padding
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 365
$System_Drawing_Size.Width = 811
$GenPage.Size = $System_Drawing_Size
$GenPage.TabIndex = 0
$GenPage.Text = "General"
$GenPage.UseVisualStyleBackColor = $True

$TabControl.Controls.Add($GenPage)
$CompInfoGrid.AllowUserToAddRows = $False
$CompInfoGrid.AllowUserToDeleteRows = $False
$CompInfoGrid.AllowUserToResizeRows = $False
$CompInfoGrid.Anchor = 12
$CompInfoGrid.ColumnHeadersVisible = $False
$System_Windows_Forms_DataGridViewTextBoxColumn_1 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_1.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_1.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_1.Width = 160

$CompInfoGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_1)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_2 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_2.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_2.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_2.Width = 620

$CompInfoGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_2)|Out-Null
$CompInfoGrid.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 3
$System_Drawing_Point.Y = 209
$CompInfoGrid.Location = $System_Drawing_Point
$CompInfoGrid.Name = "CompInfoGrid"
$CompInfoGrid.ReadOnly = $True
$CompInfoGrid.RowHeadersVisible = $False
$CompInfoGrid.SelectionMode = 1
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 153
$System_Drawing_Size.Width = 804
$CompInfoGrid.Size = $System_Drawing_Size
$CompInfoGrid.TabIndex = 7

$GenPage.Controls.Add($CompInfoGrid)

$CompInfoLbl.Anchor = 12
$CompInfoLbl.BackColor = [System.Drawing.Color]::FromArgb(255,153,180,209)
$CompInfoLbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 3
$System_Drawing_Point.Y = 184
$CompInfoLbl.Location = $System_Drawing_Point
$CompInfoLbl.Name = "CompInfoLbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 802
$CompInfoLbl.Size = $System_Drawing_Size
$CompInfoLbl.TabIndex = 6
$CompInfoLbl.Text = "Computer Information"
$CompInfoLbl.TextAlign = 32

$GenPage.Controls.Add($CompInfoLbl)

$OSLbl.Anchor = 13
$OSLbl.BackColor = [System.Drawing.Color]::FromArgb(255,153,180,209)
$OSLbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 3
$System_Drawing_Point.Y = 3
$OSLbl.Location = $System_Drawing_Point
$OSLbl.Name = "OSLbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 25
$System_Drawing_Size.Width = 802
$OSLbl.Size = $System_Drawing_Size
$OSLbl.TabIndex = 1
$OSLbl.Text = "Operating System Information"
$OSLbl.TextAlign = 32

$GenPage.Controls.Add($OSLbl)

$OSInfoGrid.AllowUserToAddRows = $False
$OSInfoGrid.AllowUserToDeleteRows = $False
$OSInfoGrid.AllowUserToResizeRows = $False
$OSInfoGrid.Anchor = 12
$OSInfoGrid.ColumnHeadersVisible = $False
$System_Windows_Forms_DataGridViewTextBoxColumn_3 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_3.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_3.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_3.Width = 160

$OSInfoGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_3)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_4 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_4.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_4.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_4.Width = 620

$OSInfoGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_4)|Out-Null
$OSInfoGrid.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 3
$System_Drawing_Point.Y = 28
$OSInfoGrid.Location = $System_Drawing_Point
$OSInfoGrid.Name = "OSInfoGrid"
$OSInfoGrid.ReadOnly = $True
$OSInfoGrid.RowHeadersVisible = $False
$OSInfoGrid.RowTemplate.Height = 24
$OSInfoGrid.SelectionMode = 1
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 153
$System_Drawing_Size.Width = 802
$OSInfoGrid.Size = $System_Drawing_Size
$OSInfoGrid.TabIndex = 0

$GenPage.Controls.Add($OSInfoGrid)


$ProgTab.BackColor = [System.Drawing.Color]::FromArgb(0,255,255,255)
$ProgTab.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 22
$ProgTab.Location = $System_Drawing_Point
$ProgTab.Name = "ProgTab"
$System_Windows_Forms_Padding = New-Object System.Windows.Forms.Padding
$System_Windows_Forms_Padding.All = 3
$System_Windows_Forms_Padding.Bottom = 3
$System_Windows_Forms_Padding.Left = 3
$System_Windows_Forms_Padding.Right = 3
$System_Windows_Forms_Padding.Top = 3
$ProgTab.Padding = $System_Windows_Forms_Padding
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 365
$System_Drawing_Size.Width = 811
$ProgTab.Size = $System_Drawing_Size
$ProgTab.TabIndex = 1
$ProgTab.Text = "Add/Remove Programs"
$ProgTab.UseVisualStyleBackColor = $True

$TabControl.Controls.Add($ProgTab)
$ReinstallBtn.Anchor = 9

$ReinstallBtn.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 730
$System_Drawing_Point.Y = 6
$ReinstallBtn.Location = $System_Drawing_Point
$ReinstallBtn.Name = "ReinstallBtn"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 75
$ReinstallBtn.Size = $System_Drawing_Size
$ReinstallBtn.TabIndex = 3
$ReinstallBtn.Text = "Reinstall"
$ReinstallBtn.UseVisualStyleBackColor = $True
$ReinstallBtn.add_Click($ReinstallBtn_OnClick)

$ProgTab.Controls.Add($ReinstallBtn)

$UninstallBtn.Anchor = 9

$UninstallBtn.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 618
$System_Drawing_Point.Y = 6
$UninstallBtn.Location = $System_Drawing_Point
$UninstallBtn.Name = "UninstallBtn"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 75
$UninstallBtn.Size = $System_Drawing_Size
$UninstallBtn.TabIndex = 2
$UninstallBtn.Text = "Uninstall"
$UninstallBtn.UseVisualStyleBackColor = $True
$UninstallBtn.add_Click($UninstallBtn_OnClick)

$ProgTab.Controls.Add($UninstallBtn)

$AddRemoveLbl.Anchor = 13
$AddRemoveLbl.BackColor = [System.Drawing.Color]::FromArgb(255,153,180,209)
$AddRemoveLbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 3
$AddRemoveLbl.Location = $System_Drawing_Point
$AddRemoveLbl.Name = "AddRemoveLbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 606
$AddRemoveLbl.Size = $System_Drawing_Size
$AddRemoveLbl.TabIndex = 1
$AddRemoveLbl.Text = "Add/Remove Programs"
$AddRemoveLbl.TextAlign = 32

$ProgTab.Controls.Add($AddRemoveLbl)

$AddRemoveGrid.AllowUserToAddRows = $False
$AddRemoveGrid.AllowUserToDeleteRows = $False
$AddRemoveGrid.AllowUserToResizeRows = $False
$AddRemoveGrid.Anchor = 15
$System_Windows_Forms_DataGridViewCellStyle_5 = New-Object System.Windows.Forms.DataGridViewCellStyle
$System_Windows_Forms_DataGridViewCellStyle_5.Alignment = 16
$System_Windows_Forms_DataGridViewCellStyle_5.BackColor = [System.Drawing.Color]::FromArgb(255,240,240,240)
$System_Windows_Forms_DataGridViewCellStyle_5.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,0,3,1)
$System_Windows_Forms_DataGridViewCellStyle_5.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)
$System_Windows_Forms_DataGridViewCellStyle_5.SelectionBackColor = [System.Drawing.Color]::FromArgb(255,51,153,255)
$System_Windows_Forms_DataGridViewCellStyle_5.SelectionForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Windows_Forms_DataGridViewCellStyle_5.WrapMode = 1
$AddRemoveGrid.ColumnHeadersDefaultCellStyle = $System_Windows_Forms_DataGridViewCellStyle_5
$AddRemoveGrid.ColumnHeadersHeightSizeMode = 1
$System_Windows_Forms_DataGridViewTextBoxColumn_6 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_6.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_6.HeaderText = "Name"
$System_Windows_Forms_DataGridViewTextBoxColumn_6.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_6.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_6.Width = 60

$AddRemoveGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_6)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_7 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_7.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_7.HeaderText = "Publisher"
$System_Windows_Forms_DataGridViewTextBoxColumn_7.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_7.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_7.Width = 75

$AddRemoveGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_7)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_8 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_8.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_8.HeaderText = "Installed On"
$System_Windows_Forms_DataGridViewTextBoxColumn_8.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_8.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_8.Width = 88

$AddRemoveGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_8)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_9 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_9.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_9.HeaderText = "Version"
$System_Windows_Forms_DataGridViewTextBoxColumn_9.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_9.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_9.Width = 67

$AddRemoveGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_9)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_10 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_10.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_10.HeaderText = "Uninstall String"
$System_Windows_Forms_DataGridViewTextBoxColumn_10.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_10.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_10.Width = 102

$AddRemoveGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_10)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_11 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_11.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_11.HeaderText = "ID Number"
$System_Windows_Forms_DataGridViewTextBoxColumn_11.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_11.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_11.Visible = $False
$System_Windows_Forms_DataGridViewTextBoxColumn_11.Width = 100

$AddRemoveGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_11)|Out-Null
$AddRemoveGrid.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Windows_Forms_DataGridViewCellStyle_12 = New-Object System.Windows.Forms.DataGridViewCellStyle
$System_Windows_Forms_DataGridViewCellStyle_12.Alignment = 16
$System_Windows_Forms_DataGridViewCellStyle_12.BackColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Windows_Forms_DataGridViewCellStyle_12.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,0,3,1)
$System_Windows_Forms_DataGridViewCellStyle_12.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)
$System_Windows_Forms_DataGridViewCellStyle_12.SelectionBackColor = [System.Drawing.Color]::FromArgb(255,51,153,255)
$System_Windows_Forms_DataGridViewCellStyle_12.SelectionForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Windows_Forms_DataGridViewCellStyle_12.WrapMode = 2
$AddRemoveGrid.DefaultCellStyle = $System_Windows_Forms_DataGridViewCellStyle_12
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 27
$AddRemoveGrid.Location = $System_Drawing_Point
$AddRemoveGrid.MultiSelect = $False
$AddRemoveGrid.Name = "AddRemoveGrid"
$AddRemoveGrid.ReadOnly = $True
$AddRemoveGrid.RowHeadersVisible = $False
$AddRemoveGrid.RowHeadersWidthSizeMode = 1
$AddRemoveGrid.SelectionMode = 1
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 332
$System_Drawing_Size.Width = 799
$AddRemoveGrid.Size = $System_Drawing_Size
$AddRemoveGrid.TabIndex = 0

$ProgTab.Controls.Add($AddRemoveGrid)


$WinUpdateTab.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 22
$WinUpdateTab.Location = $System_Drawing_Point
$WinUpdateTab.Name = "WinUpdateTab"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 365
$System_Drawing_Size.Width = 811
$WinUpdateTab.Size = $System_Drawing_Size
$WinUpdateTab.TabIndex = 9
$WinUpdateTab.Text = "Windows Updates"
$WinUpdateTab.UseVisualStyleBackColor = $True

$TabControl.Controls.Add($WinUpdateTab)
$WinUpdateView.AllowUserToAddRows = $False
$WinUpdateView.AllowUserToDeleteRows = $False
$WinUpdateView.AllowUserToResizeRows = $False
$WinUpdateView.ClipboardCopyMode = 2
$WinUpdateView.Anchor = 15
$WinUpdateView.ColumnHeadersHeightSizeMode = 1
$System_Windows_Forms_DataGridViewTextBoxColumn_13 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_13.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_13.HeaderText = "Hotfix ID"
$System_Windows_Forms_DataGridViewTextBoxColumn_13.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_13.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_13.Width = 73

$WinUpdateView.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_13)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_14 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_14.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_14.HeaderText = "Description"
$System_Windows_Forms_DataGridViewTextBoxColumn_14.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_14.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_14.Width = 85

$WinUpdateView.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_14)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_15 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_15.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_15.HeaderText = "Installed On"
$System_Windows_Forms_DataGridViewTextBoxColumn_15.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_15.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_15.Width = 88

$WinUpdateView.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_15)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_16 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_16.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_16.HeaderText = "Installed By"
$System_Windows_Forms_DataGridViewTextBoxColumn_16.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_16.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_16.Width = 86

$WinUpdateView.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_16)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_17 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_17.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_17.HeaderText = "Caption"
$System_Windows_Forms_DataGridViewTextBoxColumn_17.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_17.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_17.Width = 68

$WinUpdateView.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_17)|Out-Null
$WinUpdateView.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 3
$System_Drawing_Point.Y = 3
$WinUpdateView.Location = $System_Drawing_Point
$WinUpdateView.Name = "WinUpdateView"
$WinUpdateView.ReadOnly = $True
$WinUpdateView.SelectionMode = 1
$WinUpdateView.RowHeadersVisible = $False
$WinUpdateView.RowHeadersWidthSizeMode = 1
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 359
$System_Drawing_Size.Width = 802
$WinUpdateView.Size = $System_Drawing_Size
$WinUpdateView.TabIndex = 0

$WinUpdateTab.Controls.Add($WinUpdateView)


$ExHist.BackColor = [System.Drawing.Color]::FromArgb(0,255,255,255)
$ExHist.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 22
$ExHist.Location = $System_Drawing_Point
$ExHist.Name = "ExHist"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 365
$System_Drawing_Size.Width = 811
$ExHist.Size = $System_Drawing_Size
$ExHist.TabIndex = 6
$ExHist.Text = "Execution History"
$ExHist.UseVisualStyleBackColor = $True

$TabControl.Controls.Add($ExHist)
$ExHistGrid.AllowUserToAddRows = $False
$ExHistGrid.AllowUserToDeleteRows = $False
$ExHistGrid.AllowUserToResizeRows = $False
$ExHistGrid.Anchor = 15
$System_Windows_Forms_DataGridViewCellStyle_18 = New-Object System.Windows.Forms.DataGridViewCellStyle
$System_Windows_Forms_DataGridViewCellStyle_18.Alignment = 16
$System_Windows_Forms_DataGridViewCellStyle_18.BackColor = [System.Drawing.Color]::FromArgb(255,240,240,240)
$System_Windows_Forms_DataGridViewCellStyle_18.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,0,3,1)
$System_Windows_Forms_DataGridViewCellStyle_18.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)
$System_Windows_Forms_DataGridViewCellStyle_18.SelectionBackColor = [System.Drawing.Color]::FromArgb(255,51,153,255)
$System_Windows_Forms_DataGridViewCellStyle_18.SelectionForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Windows_Forms_DataGridViewCellStyle_18.WrapMode = 1
$ExHistGrid.ColumnHeadersDefaultCellStyle = $System_Windows_Forms_DataGridViewCellStyle_18
$System_Windows_Forms_DataGridViewTextBoxColumn_19 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_19.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_19.HeaderText = "State"
$System_Windows_Forms_DataGridViewTextBoxColumn_19.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_19.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_19.Width = 57

$ExHistGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_19)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_20 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_20.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_20.HeaderText = "User"
$System_Windows_Forms_DataGridViewTextBoxColumn_20.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_20.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_20.Width = 54

$ExHistGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_20)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_21 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_21.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_21.HeaderText = "Package ID"
$System_Windows_Forms_DataGridViewTextBoxColumn_21.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_21.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_21.Width = 89

$ExHistGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_21)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_22 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_22.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_22.HeaderText = "Name"
$System_Windows_Forms_DataGridViewTextBoxColumn_22.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_22.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_22.Width = 60

$ExHistGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_22)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_23 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_23.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_23.HeaderText = "Start Time"
$System_Windows_Forms_DataGridViewTextBoxColumn_23.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_23.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_23.Width = 80

$ExHistGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_23)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_24 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_24.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_24.HeaderText = "Error Code"
$System_Windows_Forms_DataGridViewTextBoxColumn_24.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_24.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_24.Width = 82

$ExHistGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_24)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_25 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_25.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_25.HeaderText = "Error Reason"
$System_Windows_Forms_DataGridViewTextBoxColumn_25.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_25.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_25.Width = 94

$ExHistGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_25)|Out-Null
$ExHistGrid.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Windows_Forms_DataGridViewCellStyle_26 = New-Object System.Windows.Forms.DataGridViewCellStyle
$System_Windows_Forms_DataGridViewCellStyle_26.Alignment = 16
$System_Windows_Forms_DataGridViewCellStyle_26.BackColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Windows_Forms_DataGridViewCellStyle_26.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,0,3,1)
$System_Windows_Forms_DataGridViewCellStyle_26.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)
$System_Windows_Forms_DataGridViewCellStyle_26.SelectionBackColor = [System.Drawing.Color]::FromArgb(255,51,153,255)
$System_Windows_Forms_DataGridViewCellStyle_26.SelectionForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Windows_Forms_DataGridViewCellStyle_26.WrapMode = 2
$ExHistGrid.DefaultCellStyle = $System_Windows_Forms_DataGridViewCellStyle_26
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 3
$System_Drawing_Point.Y = 3
$ExHistGrid.Location = $System_Drawing_Point
$ExHistGrid.Name = "ExHistGrid"
$ExHistGrid.ReadOnly = $True
$ExHistGrid.RowHeadersVisible = $False
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 359
$System_Drawing_Size.Width = 804
$ExHistGrid.Size = $System_Drawing_Size
$ExHistGrid.TabIndex = 1

$ExHist.Controls.Add($ExHistGrid)


$AppsTab.BackColor = [System.Drawing.Color]::FromArgb(0,255,255,255)
$AppsTab.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 22
$AppsTab.Location = $System_Drawing_Point
$AppsTab.Name = "AppsTab"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 365
$System_Drawing_Size.Width = 811
$AppsTab.Size = $System_Drawing_Size
$AppsTab.TabIndex = 7
$AppsTab.Text = "Applications"
$AppsTab.UseVisualStyleBackColor = $True

$TabControl.Controls.Add($AppsTab)
$AppGridView.AllowUserToAddRows = $False
$AppGridView.AllowUserToDeleteRows = $False
$AppGridView.AllowUserToResizeColumns = $False
$AppGridView.Anchor = 15
$System_Windows_Forms_DataGridViewCellStyle_27 = New-Object System.Windows.Forms.DataGridViewCellStyle
$System_Windows_Forms_DataGridViewCellStyle_27.Alignment = 16
$System_Windows_Forms_DataGridViewCellStyle_27.BackColor = [System.Drawing.Color]::FromArgb(255,240,240,240)
$System_Windows_Forms_DataGridViewCellStyle_27.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,0,3,1)
$System_Windows_Forms_DataGridViewCellStyle_27.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)
$System_Windows_Forms_DataGridViewCellStyle_27.SelectionBackColor = [System.Drawing.Color]::FromArgb(255,51,153,255)
$System_Windows_Forms_DataGridViewCellStyle_27.SelectionForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Windows_Forms_DataGridViewCellStyle_27.WrapMode = 1
$AppGridView.ColumnHeadersDefaultCellStyle = $System_Windows_Forms_DataGridViewCellStyle_27
$AppGridView.ColumnHeadersHeightSizeMode = 1
$System_Windows_Forms_DataGridViewTextBoxColumn_28 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_28.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_28.HeaderText = "Name"
$System_Windows_Forms_DataGridViewTextBoxColumn_28.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_28.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_28.Width = 60

$AppGridView.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_28)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_29 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_29.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_29.HeaderText = "Version"
$System_Windows_Forms_DataGridViewTextBoxColumn_29.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_29.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_29.Width = 67

$AppGridView.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_29)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_30 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_30.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_30.HeaderText = "Install State"
$System_Windows_Forms_DataGridViewTextBoxColumn_30.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_30.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_30.Width = 87

$AppGridView.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_30)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_31 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_31.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_31.HeaderText = "Last Evaluated"
$System_Windows_Forms_DataGridViewTextBoxColumn_31.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_31.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_31.Width = 103

$AppGridView.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_31)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_32 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_32.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_32.HeaderText = "Machine Target"
$System_Windows_Forms_DataGridViewTextBoxColumn_32.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_32.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_32.Width = 107

$AppGridView.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_32)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_33 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_33.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_33.HeaderText = "Deadline"
$System_Windows_Forms_DataGridViewTextBoxColumn_33.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_33.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_33.Width = 74

$AppGridView.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_33)|Out-Null
$AppGridView.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Windows_Forms_DataGridViewCellStyle_34 = New-Object System.Windows.Forms.DataGridViewCellStyle
$System_Windows_Forms_DataGridViewCellStyle_34.Alignment = 16
$System_Windows_Forms_DataGridViewCellStyle_34.BackColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Windows_Forms_DataGridViewCellStyle_34.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,0,3,1)
$System_Windows_Forms_DataGridViewCellStyle_34.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)
$System_Windows_Forms_DataGridViewCellStyle_34.SelectionBackColor = [System.Drawing.Color]::FromArgb(255,51,153,255)
$System_Windows_Forms_DataGridViewCellStyle_34.SelectionForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Windows_Forms_DataGridViewCellStyle_34.WrapMode = 2
$AppGridView.DefaultCellStyle = $System_Windows_Forms_DataGridViewCellStyle_34
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 0
$System_Drawing_Point.Y = 3
$AppGridView.Location = $System_Drawing_Point
$AppGridView.Name = "AppGridView"
$AppGridView.ReadOnly = $True
$AppGridView.RowHeadersVisible = $False
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 359
$System_Drawing_Size.Width = 807
$AppGridView.Size = $System_Drawing_Size
$AppGridView.TabIndex = 0

$AppsTab.Controls.Add($AppGridView)


$ServicesTab.BackColor = [System.Drawing.Color]::FromArgb(0,255,255,255)
$ServicesTab.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 22
$ServicesTab.Location = $System_Drawing_Point
$ServicesTab.Name = "ServicesTab"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 365
$System_Drawing_Size.Width = 811
$ServicesTab.Size = $System_Drawing_Size
$ServicesTab.TabIndex = 8
$ServicesTab.Text = "Services"
$ServicesTab.UseVisualStyleBackColor = $True

$TabControl.Controls.Add($ServicesTab)
$label5.Anchor = 10
$label5.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 479
$System_Drawing_Point.Y = 338
$label5.Location = $System_Drawing_Point
$label5.Name = "label5"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$label5.Size = $System_Drawing_Size
$label5.TabIndex = 5
$label5.Text = "Startup Type:"
$label5.TextAlign = 32

$ServicesTab.Controls.Add($label5)

$StartStopLbl.Anchor = 6
$StartStopLbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 3
$System_Drawing_Point.Y = 334
$StartStopLbl.Location = $System_Drawing_Point
$StartStopLbl.Name = "StartStopLbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$StartStopLbl.Size = $System_Drawing_Size
$StartStopLbl.TabIndex = 4
$StartStopLbl.Text = "Start / Stop"
$StartStopLbl.TextAlign = 32

$ServicesTab.Controls.Add($StartStopLbl)

$StartupTypeBox.Anchor = 10
$StartupTypeBox.DataBindings.DefaultDataSourceUpdateMode = 0
$StartupTypeBox.DropDownStyle = 2
$StartupTypeBox.FormattingEnabled = $True
$StartupTypeBox.Items.Add("Automatic")|Out-Null
$StartupTypeBox.Items.Add("Manual")|Out-Null
$StartupTypeBox.Items.Add("Disabled")|Out-Null
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 609
$System_Drawing_Point.Y = 338
$StartupTypeBox.Location = $System_Drawing_Point
$StartupTypeBox.Name = "StartupTypeBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 160
$StartupTypeBox.Size = $System_Drawing_Size
$StartupTypeBox.TabIndex = 3
$StartupTypeBox.add_DropDownClosed($StartupTypeBox_OnChange)

$ServicesTab.Controls.Add($StartupTypeBox)

$StartStopServBox.Anchor = 6
$StartStopServBox.DataBindings.DefaultDataSourceUpdateMode = 0
$StartStopServBox.DropDownStyle = 2
$StartStopServBox.FormattingEnabled = $True
$StartStopServBox.Items.Add("Start")|Out-Null
$StartStopServBox.Items.Add("Stop")|Out-Null
$StartStopServBox.Items.Add("Pause")|Out-Null
$StartStopServBox.Items.Add("Resume")|Out-Null
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 109
$System_Drawing_Point.Y = 336
$StartStopServBox.Location = $System_Drawing_Point
$StartStopServBox.Name = "StartStopServBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 160
$StartStopServBox.Size = $System_Drawing_Size
$StartStopServBox.TabIndex = 2
$StartStopServBox.add_DropDownClosed($StartStopServBox_OnChange)

$ServicesTab.Controls.Add($StartStopServBox)

$ServicesGridView.AllowUserToAddRows = $False
$ServicesGridView.AllowUserToDeleteRows = $False
$ServicesGridView.AllowUserToResizeRows = $False
$ServicesGridView.Anchor = 15
$System_Windows_Forms_DataGridViewCellStyle_35 = New-Object System.Windows.Forms.DataGridViewCellStyle
$System_Windows_Forms_DataGridViewCellStyle_35.Alignment = 16
$System_Windows_Forms_DataGridViewCellStyle_35.BackColor = [System.Drawing.Color]::FromArgb(255,240,240,240)
$System_Windows_Forms_DataGridViewCellStyle_35.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,0,3,1)
$System_Windows_Forms_DataGridViewCellStyle_35.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)
$System_Windows_Forms_DataGridViewCellStyle_35.SelectionBackColor = [System.Drawing.Color]::FromArgb(255,51,153,255)
$System_Windows_Forms_DataGridViewCellStyle_35.SelectionForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Windows_Forms_DataGridViewCellStyle_35.WrapMode = 1
$ServicesGridView.ColumnHeadersDefaultCellStyle = $System_Windows_Forms_DataGridViewCellStyle_35
$ServicesGridView.ColumnHeadersHeightSizeMode = 1
$System_Windows_Forms_DataGridViewTextBoxColumn_36 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_36.HeaderText = "Display Name"
$System_Windows_Forms_DataGridViewTextBoxColumn_36.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_36.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_36.Width = 150

$ServicesGridView.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_36)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_37 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_37.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_37.HeaderText = "Name"
$System_Windows_Forms_DataGridViewTextBoxColumn_37.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_37.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_37.Width = 60

$ServicesGridView.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_37)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_38 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_38.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_38.HeaderText = "Status"
$System_Windows_Forms_DataGridViewTextBoxColumn_38.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_38.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_38.Width = 62

$ServicesGridView.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_38)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_39 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_39.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_39.HeaderText = "Startup Type"
$System_Windows_Forms_DataGridViewTextBoxColumn_39.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_39.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_39.Width = 93

$ServicesGridView.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_39)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_40 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_40.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_40.HeaderText = "Description"
$System_Windows_Forms_DataGridViewTextBoxColumn_40.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_40.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_40.Width = 85

$ServicesGridView.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_40)|Out-Null
$ServicesGridView.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Windows_Forms_DataGridViewCellStyle_41 = New-Object System.Windows.Forms.DataGridViewCellStyle
$System_Windows_Forms_DataGridViewCellStyle_41.Alignment = 16
$System_Windows_Forms_DataGridViewCellStyle_41.BackColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Windows_Forms_DataGridViewCellStyle_41.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,0,3,1)
$System_Windows_Forms_DataGridViewCellStyle_41.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)
$System_Windows_Forms_DataGridViewCellStyle_41.SelectionBackColor = [System.Drawing.Color]::FromArgb(255,51,153,255)
$System_Windows_Forms_DataGridViewCellStyle_41.SelectionForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Windows_Forms_DataGridViewCellStyle_41.WrapMode = 2
$ServicesGridView.DefaultCellStyle = $System_Windows_Forms_DataGridViewCellStyle_41
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 0
$System_Drawing_Point.Y = 3
$ServicesGridView.Location = $System_Drawing_Point
$ServicesGridView.MultiSelect = $False
$ServicesGridView.Name = "ServicesGridView"
$ServicesGridView.ReadOnly = $True
$ServicesGridView.RowHeadersVisible = $False
$ServicesGridView.SelectionMode = 1
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 325
$System_Drawing_Size.Width = 808
$ServicesGridView.Size = $System_Drawing_Size
$ServicesGridView.TabIndex = 0
$ServicesGridView.add_Click($ServicesGridView_OnClick)

$ServicesTab.Controls.Add($ServicesGridView)


$Drivers.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 4
$System_Drawing_Point.Y = 22
$Drivers.Location = $System_Drawing_Point
$Drivers.Name = "Drivers"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 365
$System_Drawing_Size.Width = 811
$Drivers.Size = $System_Drawing_Size
$Drivers.TabIndex = 10
$Drivers.Text = "Drivers"
$Drivers.UseVisualStyleBackColor = $True

$TabControl.Controls.Add($Drivers)
$DriverGrid.AllowUserToAddRows = $False
$DriverGrid.AllowUserToDeleteRows = $False
$DriverGrid.AllowUserToResizeRows = $False
$DriverGrid.Anchor = 15
$System_Windows_Forms_DataGridViewCellStyle_42 = New-Object System.Windows.Forms.DataGridViewCellStyle
$System_Windows_Forms_DataGridViewCellStyle_42.Alignment = 16
$System_Windows_Forms_DataGridViewCellStyle_42.BackColor = [System.Drawing.Color]::FromArgb(255,240,240,240)
$System_Windows_Forms_DataGridViewCellStyle_42.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,0,3,0)
$System_Windows_Forms_DataGridViewCellStyle_42.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)
$System_Windows_Forms_DataGridViewCellStyle_42.SelectionBackColor = [System.Drawing.Color]::FromArgb(255,51,153,255)
$System_Windows_Forms_DataGridViewCellStyle_42.SelectionForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Windows_Forms_DataGridViewCellStyle_42.WrapMode = 1
$DriverGrid.ColumnHeadersDefaultCellStyle = $System_Windows_Forms_DataGridViewCellStyle_42
$DriverGrid.ColumnHeadersHeightSizeMode = 1
$System_Windows_Forms_DataGridViewTextBoxColumn_43 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_43.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_43.HeaderText = "Device Name"
$System_Windows_Forms_DataGridViewTextBoxColumn_43.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_43.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_43.Width = 97

$DriverGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_43)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_44 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_44.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_44.HeaderText = "Device Class"
$System_Windows_Forms_DataGridViewTextBoxColumn_44.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_44.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_44.Width = 94

$DriverGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_44)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_45 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_45.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_45.HeaderText = "Driver Date"
$System_Windows_Forms_DataGridViewTextBoxColumn_45.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_45.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_45.Width = 86

$DriverGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_45)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_46 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_46.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_46.HeaderText = "Driver Version"
$System_Windows_Forms_DataGridViewTextBoxColumn_46.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_46.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_46.Width = 98

$DriverGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_46)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_47 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_47.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_47.HeaderText = "Is Signed"
$System_Windows_Forms_DataGridViewTextBoxColumn_47.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_47.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_47.Width = 76

$DriverGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_47)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_48 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_48.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_48.HeaderText = "Device ID"
$System_Windows_Forms_DataGridViewTextBoxColumn_48.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_48.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_48.Width = 80

$DriverGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_48)|Out-Null
$DriverGrid.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Windows_Forms_DataGridViewCellStyle_49 = New-Object System.Windows.Forms.DataGridViewCellStyle
$System_Windows_Forms_DataGridViewCellStyle_49.Alignment = 16
$System_Windows_Forms_DataGridViewCellStyle_49.BackColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Windows_Forms_DataGridViewCellStyle_49.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,0,3,0)
$System_Windows_Forms_DataGridViewCellStyle_49.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)
$System_Windows_Forms_DataGridViewCellStyle_49.SelectionBackColor = [System.Drawing.Color]::FromArgb(255,51,153,255)
$System_Windows_Forms_DataGridViewCellStyle_49.SelectionForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Windows_Forms_DataGridViewCellStyle_49.WrapMode = 2
$DriverGrid.DefaultCellStyle = $System_Windows_Forms_DataGridViewCellStyle_49
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 3
$System_Drawing_Point.Y = 3
$DriverGrid.Location = $System_Drawing_Point
$DriverGrid.Name = "DriverGrid"
$DriverGrid.ReadOnly = $True
$DriverGrid.RowHeadersVisible = $False
$DriverGrid.RowHeadersWidthSizeMode = 1
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 359
$System_Drawing_Size.Width = 805
$DriverGrid.Size = $System_Drawing_Size
$DriverGrid.TabIndex = 0

$Drivers.Controls.Add($DriverGrid)



$CloseBtn.Anchor = 10

$CloseBtn.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 746
$System_Drawing_Point.Y = 409
$CloseBtn.Location = $System_Drawing_Point
$CloseBtn.Name = "CloseBtn"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$CloseBtn.Size = $System_Drawing_Size
$CloseBtn.TabIndex = 3
$CloseBtn.Text = "Close"
$CloseBtn.UseVisualStyleBackColor = $True
$CloseBtn.add_Click($CloseBtn_OnClick)

$form1.Controls.Add($CloseBtn)

#endregion Generated Form Code

$InitialFormWindowState = $form1.WindowState
$form1.add_Load($OnLoadForm_StateCorrection)
$form1.add_SizeChanged($ResizeEnd)
$form1.ShowDialog()| Out-Null

}

GenerateForm