<#
Written by Ryan Ephgrave for ConfigMgr 2012 Right Click Tools
http://psrightclicktools.codeplex.com/
GUI Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
#>

$ResourceID = $args[0]
$Server = $args[1]
$Namespace = $args[2]

$strQuery = "Select ResourceID,ResourceNames from SMS_R_System where ResourceID='$ResourceID'"
Get-WmiObject -Query $strQuery -Namespace $Namespace -ComputerName $Server | ForEach-Object {$CompName = $_.ResourceNames[0]}

$Popup = new-object -comobject wscript.shell
$GetDirectory = $MyInvocation.MyCommand.path
$Directory = Split-Path $GetDirectory

function GenerateForm {

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$AboutBtn = New-Object System.Windows.Forms.Button
$Close = New-Object System.Windows.Forms.Button
$Refresh = New-Object System.Windows.Forms.Button
$KillProc = New-Object System.Windows.Forms.Button
$ProcessGridView = New-Object System.Windows.Forms.DataGridView
$TitleLbl = New-Object System.Windows.Forms.Label
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects


$Close_OnClick= 
{
	$ProcessID = [System.Diagnostics.Process]::GetCurrentProcess()
	$ProcID = $ProcessID.ID
	& taskkill /PID $ProcID /T /F
}

$AboutBtn_OnClick= 
{
	$ArgList = @()
	$ArgList += @("`"$Directory\SilentOpenPS.vbs`"")
	$ArgList += @("`"$Directory\About.ps1`"")
	Start-Process wscript.exe -ArgumentList $ArgList
}

$Refresh_OnClick= 
{
	$ProcessGridView.Rows.Clear()
	$strQuery = "select WorkingSetPrivate,IDProcess from Win32_PerfFormattedData_PerfProc_Process"
	Get-WmiObject -ComputerName $CompName -Namespace root\cimv2 -Query $strQuery | ForEach-Object {
		$ProcID = $_.IDProcess
		$WorkingSet = $_.WorkingSetPrivate
		$ProcMemory = $WorkingSet / 1024
		$strQuery = "Select * from Win32_Process where ProcessID='" + $ProcID + "'"
		$ProcessInfo = Get-WmiObject -ComputerName $CompName -Query $strQuery -Namespace root\cimv2
		foreach ($instance in $ProcessInfo){
			$ProcName = $instance.Name
			$ProcExcPath = $instance.ExecutablePath
			$ProcUser = $ProcessInfo.GetOwner().User
		}
		$ProcessGridView.Rows.Add($ProcID,$ProcName,$ProcExcPath,$ProcUser,$ProcMemory)
	}
}

$KillProc_OnClick= 
{
	$ProcessGridView.SelectedRows | ForEach-Object {$RowIndex = $_.index}
	$ProcName = $ProcessGridView.Rows[$RowIndex].Cells[1].Value
	$ProcID = $ProcessGridView.Rows[$RowIndex].Cells[0].Value
	$PopupAnswer = $Popup.popup("Do you want to kill process $ProcName",0,"Are you sure?",1)
	if ($PopupAnswer -eq 1){
		$Error.Clear()
		$strQuery = "Select * from Win32_Process where ProcessID='" + $ProcID + "'"
		Get-WmiObject -ComputerName $CompName -Query $strQuery -Namespace root\cimv2 | ForEach-Object {$_.Terminate()}
		if ($Error[0]){$Popup.Popup("Error terminating process $ProcName",0,"Error",16)}
		else {$Popup.Popup("Successfully terminated process $ProcName",0,"Successful",0)}
	}
}

$OnLoadForm_StateCorrection=
{
	$form1.WindowState = $InitialFormWindowState
	$strQuery = "select WorkingSetPrivate,IDProcess from Win32_PerfFormattedData_PerfProc_Process"
	Get-WmiObject -ComputerName $CompName -Namespace root\cimv2 -Query $strQuery | ForEach-Object {
		$ProcID = $_.IDProcess
		$WorkingSet = $_.WorkingSetPrivate
		$ProcMemory = $WorkingSet / 1024
		$strQuery = "Select * from Win32_Process where ProcessID='" + $ProcID + "'"
		$ProcessInfo = Get-WmiObject -ComputerName $CompName -Query $strQuery -Namespace root\cimv2
		foreach ($instance in $ProcessInfo){
			$ProcName = $instance.Name
			$ProcExcPath = $instance.ExecutablePath
			$ProcUser = $ProcessInfo.GetOwner().User
		}
		$ProcessGridView.Rows.Add($ProcID,$ProcName,$ProcExcPath,$ProcUser,$ProcMemory)
	}
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 469
$System_Drawing_Size.Width = 733
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.Name = "form1"
$form1.Text = "Running Processes - $CompName"

$AboutBtn.Anchor = 6

$AboutBtn.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 438
$AboutBtn.Location = $System_Drawing_Point
$AboutBtn.Name = "AboutBtn"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$AboutBtn.Size = $System_Drawing_Size
$AboutBtn.TabIndex = 6
$AboutBtn.Text = "About"
$AboutBtn.UseVisualStyleBackColor = $True
$AboutBtn.add_Click($AboutBtn_OnClick)

$form1.Controls.Add($AboutBtn)

$Close.Anchor = 10

$Close.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 646
$System_Drawing_Point.Y = 438
$Close.Location = $System_Drawing_Point
$Close.Name = "Close"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$Close.Size = $System_Drawing_Size
$Close.TabIndex = 5
$Close.Text = "Close"
$Close.UseVisualStyleBackColor = $True
$Close.add_Click($Close_OnClick)

$form1.Controls.Add($Close)

$Refresh.Anchor = 10

$Refresh.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 542
$System_Drawing_Point.Y = 438
$Refresh.Location = $System_Drawing_Point
$Refresh.Name = "Refresh"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$Refresh.Size = $System_Drawing_Size
$Refresh.TabIndex = 4
$Refresh.Text = "Refresh"
$Refresh.UseVisualStyleBackColor = $True
$Refresh.add_Click($Refresh_OnClick)

$form1.Controls.Add($Refresh)

$KillProc.Anchor = 10

$KillProc.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 430
$System_Drawing_Point.Y = 438
$KillProc.Location = $System_Drawing_Point
$KillProc.Name = "KillProc"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$KillProc.Size = $System_Drawing_Size
$KillProc.TabIndex = 2
$KillProc.Text = "Kill Process"
$KillProc.UseVisualStyleBackColor = $True
$KillProc.add_Click($KillProc_OnClick)

$form1.Controls.Add($KillProc)

$ProcessGridView.AllowUserToAddRows = $False
$ProcessGridView.AllowUserToDeleteRows = $False
$ProcessGridView.AllowUserToResizeRows = $False
$ProcessGridView.Anchor = 15
$ProcessGridView.ClipboardCopyMode = 2
$System_Windows_Forms_DataGridViewCellStyle_15 = New-Object System.Windows.Forms.DataGridViewCellStyle
$System_Windows_Forms_DataGridViewCellStyle_15.Alignment = 16
$System_Windows_Forms_DataGridViewCellStyle_15.BackColor = [System.Drawing.Color]::FromArgb(255,240,240,240)
$System_Windows_Forms_DataGridViewCellStyle_15.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,0,3,1)
$System_Windows_Forms_DataGridViewCellStyle_15.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)
$System_Windows_Forms_DataGridViewCellStyle_15.SelectionBackColor = [System.Drawing.Color]::FromArgb(255,51,153,255)
$System_Windows_Forms_DataGridViewCellStyle_15.SelectionForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Windows_Forms_DataGridViewCellStyle_15.WrapMode = 1
$ProcessGridView.ColumnHeadersDefaultCellStyle = $System_Windows_Forms_DataGridViewCellStyle_15
$ProcessGridView.ColumnHeadersHeightSizeMode = 1
$System_Windows_Forms_DataGridViewTextBoxColumn_16 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_16.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_16.HeaderText = "PID"
$System_Windows_Forms_DataGridViewTextBoxColumn_16.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_16.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_16.Width = 50

$ProcessGridView.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_16)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_17 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_17.HeaderText = "Process Name"
$System_Windows_Forms_DataGridViewTextBoxColumn_17.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_17.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_17.Width = 150

$ProcessGridView.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_17)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_18 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_18.HeaderText = "Executable Path"
$System_Windows_Forms_DataGridViewTextBoxColumn_18.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_18.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_18.Width = 300

$ProcessGridView.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_18)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_19 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_19.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_19.HeaderText = "Username"
$System_Windows_Forms_DataGridViewTextBoxColumn_19.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_19.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_19.Width = 80

$ProcessGridView.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_19)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_20 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_20.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_20.HeaderText = "Memory"
$System_Windows_Forms_DataGridViewTextBoxColumn_20.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_20.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_20.Width = 69

$ProcessGridView.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_20)|Out-Null
$ProcessGridView.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Windows_Forms_DataGridViewCellStyle_21 = New-Object System.Windows.Forms.DataGridViewCellStyle
$System_Windows_Forms_DataGridViewCellStyle_21.Alignment = 16
$System_Windows_Forms_DataGridViewCellStyle_21.BackColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Windows_Forms_DataGridViewCellStyle_21.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,0,3,1)
$System_Windows_Forms_DataGridViewCellStyle_21.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)
$System_Windows_Forms_DataGridViewCellStyle_21.SelectionBackColor = [System.Drawing.Color]::FromArgb(255,51,153,255)
$System_Windows_Forms_DataGridViewCellStyle_21.SelectionForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Windows_Forms_DataGridViewCellStyle_21.WrapMode = 2
$ProcessGridView.DefaultCellStyle = $System_Windows_Forms_DataGridViewCellStyle_21
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 35
$ProcessGridView.Location = $System_Drawing_Point
$ProcessGridView.Name = "ProcessGridView"
$ProcessGridView.ReadOnly = $True
$ProcessGridView.RowHeadersVisible = $False
$ProcessGridView.RowHeadersWidthSizeMode = 1
$ProcessGridView.SelectionMode = 1
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 397
$System_Drawing_Size.Width = 709
$ProcessGridView.Size = $System_Drawing_Size
$ProcessGridView.TabIndex = 1

$form1.Controls.Add($ProcessGridView)

$TitleLbl.Anchor = 13
$TitleLbl.BackColor = [System.Drawing.Color]::FromArgb(255,153,180,209)
$TitleLbl.DataBindings.DefaultDataSourceUpdateMode = 0
$TitleLbl.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 9
$TitleLbl.Location = $System_Drawing_Point
$TitleLbl.Name = "TitleLbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 709
$TitleLbl.Size = $System_Drawing_Size
$TitleLbl.TabIndex = 0
$TitleLbl.Text = "Running Processes on $CompName"
$TitleLbl.TextAlign = 32

$form1.Controls.Add($TitleLbl)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null

}

if (Test-Connection -computername $CompName -count 1 -quiet){GenerateForm}
else {$Popup.Popup("Error, cannot ping $CompName",0,"Error",16)}
