<#
Written by Ryan Ephgrave for ConfigMgr 2012 Right Click Tools
http://psrightclicktools.codeplex.com/
GUI Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
#>

$ResourceID = $args[0]
$Server = $args[1]
$Namespace = $args[2]

$strQuery = "Select ResourceID,ResourceNames from SMS_R_System where ResourceID='$ResourceID'"
Get-WmiObject -Query $strQuery -Namespace $Namespace -ComputerName $Server | ForEach-Object {$CompName = $_.ResourceNames[0]}

$Popup = new-object -comobject wscript.shell

$GetDirectory = $MyInvocation.MyCommand.path
$Directory = Split-Path $GetDirectory

function GenerateForm {

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$AboutBtn = New-Object System.Windows.Forms.Button
$Close = New-Object System.Windows.Forms.Button
$ReRun = New-Object System.Windows.Forms.Button
$AdvListGrid = New-Object System.Windows.Forms.DataGridView
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects


$Close_OnClick= 
{
	$ProcessID = [System.Diagnostics.Process]::GetCurrentProcess()
	$ProcID = $ProcessID.ID
	& taskkill /PID $ProcID /T /F
}

$AboutBtn_OnClick= 
{
	$ArgList = @()
	$ArgList += @("`"$Directory\SilentOpenPS.vbs`"")
	$ArgList += @("`"$Directory\About.ps1`"")
	Start-Process wscript.exe -ArgumentList $ArgList
}

$ReRun_OnClick= 
{
	$AdvListGrid.SelectedRows | ForEach-Object {$RowIndex = $_.index}
	$AdvName = $AdvListGrid.Rows[$RowIndex].Cells[0].Value
	$AdvID = $AdvListGrid.Rows[$RowIndex].Cells[1].Value
	$PopupAnswer = $Popup.Popup("Do you want to rerun $AdvName on $CompName",0,"Are you sure?",1)
	if ($PopupAnswer -eq 1){
		$Error.Clear()
		$strQuery = "Select * from CCM_Scheduler_ScheduledMessage where ScheduledMessageID like '" + $AdvID + "%'"
		$objSMSSchID = Get-WmiObject -Query $strQuery -Namespace root\ccm\policy\machine\actualconfig -computername $CompName
		foreach($instance in $objSMSSchID){$strScheduleID = $instance.ScheduledMessageID}
		if ($Error[0]){
			$Popup.Popup("Error connecting to WMI",0,"Error",16)
			break
		}
		else {
			$strQuery = "Select * from CCM_SoftwareDistribution where ADV_AdvertisementID='" + $AdvID + "'"
			Get-WmiObject -ComputerName $CompName -Namespace "root\CCM\Policy\Machine\ActualConfig" -Query $strQuery | ForEach-Object {
				$_.ADV_MandatoryAssignments = "True"
				$_.ADV_RepeatRunBehavior = "RerunAlways"
				[Void]$_.Put()
			}
			$WMIPath = "\\" + $CompName + "\root\ccm:SMS_Client"
			$SMSwmi = [wmiclass] $WMIPath
			[Void]$SMSwmi.TriggerSchedule($strScheduleID)
			if ($Error[0]){$Popup.Popup("Error triggering rerun",0,"Error",16)}
			else {$Popup.Popup("Successfully reran $AdvName",0,"Successful",0)}
		}
	}
}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
	Get-WmiObject -ComputerName $CompName -Namespace "root\CCM\Policy\Machine\ActualConfig" -Class "CCM_SoftwareDistribution" | ForEach-Object {
		$PackageName = $_.PKG_Name
		$AdvID = $_.ADV_AdvertisementID
		$PRFDisable = $_.PRG_PRF_Disabled
		if ($PRFDisable -eq $false){$AdvListGrid.rows.add($PackageName,$AdvID)}
	}
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 431
$System_Drawing_Size.Width = 455
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.Name = "form1"
$form1.Text = "Rerun Advertisement $CompName"

$AboutBtn.Anchor = 6

$AboutBtn.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 399
$AboutBtn.Location = $System_Drawing_Point
$AboutBtn.Name = "AboutBtn"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$AboutBtn.Size = $System_Drawing_Size
$AboutBtn.TabIndex = 3
$AboutBtn.Text = "About"
$AboutBtn.UseVisualStyleBackColor = $True
$AboutBtn.add_Click($AboutBtn_OnClick)

$form1.Controls.Add($AboutBtn)

$Close.Anchor = 10

$Close.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 364
$System_Drawing_Point.Y = 399
$Close.Location = $System_Drawing_Point
$Close.Name = "Close"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$Close.Size = $System_Drawing_Size
$Close.TabIndex = 2
$Close.Text = "Close"
$Close.UseVisualStyleBackColor = $True
$Close.add_Click($Close_OnClick)

$form1.Controls.Add($Close)

$ReRun.Anchor = 10

$ReRun.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 199
$System_Drawing_Point.Y = 399
$ReRun.Location = $System_Drawing_Point
$ReRun.Name = "ReRun"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 137
$ReRun.Size = $System_Drawing_Size
$ReRun.TabIndex = 1
$ReRun.Text = "Rerun Advertisement"
$ReRun.UseVisualStyleBackColor = $True
$ReRun.add_Click($ReRun_OnClick)

$form1.Controls.Add($ReRun)

$AdvListGrid.AllowUserToAddRows = $False
$AdvListGrid.AllowUserToDeleteRows = $False
$AdvListGrid.AllowUserToResizeRows = $False
$AdvListGrid.Anchor = 15
$System_Windows_Forms_DataGridViewCellStyle_9 = New-Object System.Windows.Forms.DataGridViewCellStyle
$System_Windows_Forms_DataGridViewCellStyle_9.Alignment = 16
$System_Windows_Forms_DataGridViewCellStyle_9.BackColor = [System.Drawing.Color]::FromArgb(255,240,240,240)
$System_Windows_Forms_DataGridViewCellStyle_9.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,0,3,0)
$System_Windows_Forms_DataGridViewCellStyle_9.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)
$System_Windows_Forms_DataGridViewCellStyle_9.SelectionBackColor = [System.Drawing.Color]::FromArgb(255,51,153,255)
$System_Windows_Forms_DataGridViewCellStyle_9.SelectionForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Windows_Forms_DataGridViewCellStyle_9.WrapMode = 1
$AdvListGrid.ColumnHeadersDefaultCellStyle = $System_Windows_Forms_DataGridViewCellStyle_9
$AdvListGrid.ColumnHeadersHeightSizeMode = 1
$System_Windows_Forms_DataGridViewTextBoxColumn_10 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_10.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_10.HeaderText = "Package Name"
$System_Windows_Forms_DataGridViewTextBoxColumn_10.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_10.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_10.Width = 106

$AdvListGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_10)|Out-Null
$System_Windows_Forms_DataGridViewTextBoxColumn_11 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
$System_Windows_Forms_DataGridViewTextBoxColumn_11.AutoSizeMode = 6
$System_Windows_Forms_DataGridViewTextBoxColumn_11.HeaderText = "Package ID"
$System_Windows_Forms_DataGridViewTextBoxColumn_11.Name = ""
$System_Windows_Forms_DataGridViewTextBoxColumn_11.ReadOnly = $True
$System_Windows_Forms_DataGridViewTextBoxColumn_11.Width = 89

$AdvListGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_11)|Out-Null
$AdvListGrid.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Windows_Forms_DataGridViewCellStyle_12 = New-Object System.Windows.Forms.DataGridViewCellStyle
$System_Windows_Forms_DataGridViewCellStyle_12.Alignment = 16
$System_Windows_Forms_DataGridViewCellStyle_12.BackColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Windows_Forms_DataGridViewCellStyle_12.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,0,3,0)
$System_Windows_Forms_DataGridViewCellStyle_12.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)
$System_Windows_Forms_DataGridViewCellStyle_12.SelectionBackColor = [System.Drawing.Color]::FromArgb(255,51,153,255)
$System_Windows_Forms_DataGridViewCellStyle_12.SelectionForeColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Windows_Forms_DataGridViewCellStyle_12.WrapMode = 2
$AdvListGrid.DefaultCellStyle = $System_Windows_Forms_DataGridViewCellStyle_12
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 12
$AdvListGrid.Location = $System_Drawing_Point
$AdvListGrid.MultiSelect = $False
$AdvListGrid.Name = "AdvListGrid"
$AdvListGrid.ReadOnly = $True
$AdvListGrid.RowHeadersVisible = $False
$AdvListGrid.RowHeadersWidthSizeMode = 1
$AdvListGrid.SelectionMode = 1
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 378
$System_Drawing_Size.Width = 427
$AdvListGrid.Size = $System_Drawing_Size
$AdvListGrid.TabIndex = 0

$form1.Controls.Add($AdvListGrid)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null

}

if (Test-Connection -computername $CompName -count 1 -quiet){GenerateForm}
else {$Popup.Popup("Error, cannot ping $CompName",0,"Error",16)}