<#
Written by Ryan Ephgrave for ConfigMgr 2012 Right Click Tools
http://psrightclicktools.codeplex.com/
GUI Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
#>

$GetDirectory = $MyInvocation.MyCommand.path
$Directory = Split-Path $GetDirectory
$Popup = new-object -comobject wscript.shell
$ErrorActionPreference = "SilentlyContinue"
$Version = "1.5.003"

function GenerateForm {

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
#endregion

#region Generated Form Objects
$InstallForm = New-Object System.Windows.Forms.Form
$RemoveOldToolsBox = New-Object System.Windows.Forms.CheckBox
$ConfigInstallBrowse = New-Object System.Windows.Forms.Button
$ConfigMgrInstallLocBox = New-Object System.Windows.Forms.TextBox
$ConfigMgrLbl = New-Object System.Windows.Forms.Label
$InstallToBrowse = New-Object System.Windows.Forms.Button
$InstallToBox = New-Object System.Windows.Forms.TextBox
$InstallToLbl = New-Object System.Windows.Forms.Label
$PSToolsLbl = New-Object System.Windows.Forms.Label
$CancelBtn = New-Object System.Windows.Forms.Button
$NextBtn = New-Object System.Windows.Forms.Button
$openFolderDialog = New-Object System.Windows.Forms.FolderBrowserDialog
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects


$Cancel_Btn= 
{
	$InstallForm.close()
}

$Install_Browse= 
{
	$openFolderDialog.SelectedPath = $null
	$openFolderDialog.ShowDialog()
	if (Test-Path $openFolderDialog.SelectedPath) {$InstallToBox.Text = $openFolderDialog.SelectedPath}
}

$Config_Browse= 
{
	$openFolderDialog.SelectedPath = $null
	$openFolderDialog.ShowDialog()
	if (Test-Path $openFolderDialog.SelectedPath) {$ConfigMgrInstallLocBox.Text = $openFolderDialog.SelectedPath}
}

$Install_Btn= 
{
	$MenuinstallPath = $ConfigMgrInstallLocBox.Text
	if ($MenuInstallPath.Endswith("\")) {$MenuInstallPath = $MenuInstallPath.Substring(0,$MenuInstallPath.Length -1)}
	$MenuinstallPath = $MenuinstallPath.replace("`n","").replace("`r","")
	$TestAdminConsole = Test-Path "$MenuInstallPath\AdminConsole"
	if ($TestAdminConsole) {$MenuinstallPath = "$MenuInstallPath\AdminConsole"}
	$TestPath = "$MenuInstallpath"
	$Error.Clear()
	if (Test-Path $TestPath) {
	$PopupAnswer = $Popup.popup("Are you sure you want to install the Powershell Right Click Tools?",0,"Are you sure?",1)
	if ($PopupAnswer -eq 1) {
        $AdminConsolePath = "$MenuinstallPath\AdminConsole"
		if (Test-Path $AdminConsolePath) {$XMLInstallPath = "$MenuInstallPath\AdminConsole\XMLStorage\Extensions\Actions"}
		else {$XMLInstallPath = "$MenuinstallPath\XMLStorage\Extensions\Actions"}
		$ToolInstallPath = $InstallToBox.Text
		$ToolInstallPath = $ToolInstallPath.replace("`n","")
		if ($ToolInstallPath.Endswith("\")) {$ToolInstallPath = $ToolInstallPath.Substring(0,$ToolInstallPath.Length -1)}
		$RemoveTools = $RemoveOldToolsBox.Checked
		if ($RemoveTools -eq $true) {
			if (Test-Path "C:\Program Files\SCCMConsoleExtensions") {Remove-Item "c:\Program Files\SCCMConsoleExtensions" -Force -Recurse}
			Remove-Item "$XMLInstallPath\3fd01cd1-9e01-461e-92cd-94866b8d1f39\Right Click Tools - Client Actions.xml" -force -ErrorAction SilentlyContinue
			Remove-Item "$XMLInstallPath\3fd01cd1-9e01-461e-92cd-94866b8d1f39\Right Click Tools - Client Tools.xml" -force -ErrorAction SilentlyContinue
			Remove-Item "$XMLInstallPath\3fd01cd1-9e01-461e-92cd-94866b8d1f39\Right Click Tools - Console Tools.xml" -force -ErrorAction SilentlyContinue
			Remove-Item "$XMLInstallPath\ed9dee86-eadd-4ac8-82a1-7234a4646e62\Right Click Tools - Client Actions.xml" -force -ErrorAction SilentlyContinue
			Remove-Item "$XMLInstallPath\ed9dee86-eadd-4ac8-82a1-7234a4646e62\Right Click Tools - Client Tools.xml" -force -ErrorAction SilentlyContinue
			Remove-Item "$XMLInstallPath\ed9dee86-eadd-4ac8-82a1-7234a4646e62\Right Click Tools - Console Tools.xml" -force -ErrorAction SilentlyContinue
			Remove-Item "$XMLInstallPath\3785759b-db2c-414e-a540-e879497c6f97\SCCM-Client Actions(Collection).xml" -force -ErrorAction SilentlyContinue
			Remove-Item "$XMLInstallPath\3785759b-db2c-414e-a540-e879497c6f97\SCCM-Client Tools(Collection).xml" -force -ErrorAction SilentlyContinue
			Remove-Item "$XMLInstallPath\3785759b-db2c-414e-a540-e879497c6f97\SCCM-Console Tools(Collection).xml" -force -ErrorAction SilentlyContinue
			Remove-Item "$XMLInstallPath\a92615d6-9df3-49ba-a8c9-6ecb0e8b956b\SCCM-Client Actions(Collection).xml" -force -ErrorAction SilentlyContinue
			Remove-Item "$XMLInstallPath\a92615d6-9df3-49ba-a8c9-6ecb0e8b956b\SCCM-Client Tools(Collection).xml" -force -ErrorAction SilentlyContinue
			Remove-Item "$XMLInstallPath\a92615d6-9df3-49ba-a8c9-6ecb0e8b956b\SCCM-Console Tools(Collection).xml" -force -ErrorAction SilentlyContinue
		}
		& xcopy "$Directory" "$ToolInstallPath\" /e /f /y
		
		Remove-Item "$ToolInstallPath\Default Menus\Device\Client Actions on Device.xml" -Force -ErrorAction SilentlyContinue
		Remove-Item "$ToolInstallPath\Default Menus\Device\Client Tools on Device.xml" -Force -ErrorAction SilentlyContinue
		Remove-Item "$ToolInstallPath\Default Menus\Device\Console Tools on Device.xml" -Force -ErrorAction SilentlyContinue
		Remove-Item "$ToolInstallPath\Default Menus\Collection\Client Actions on Collection.xml" -Force -ErrorAction SilentlyContinue
		Remove-Item "$ToolInstallPath\Default Menus\Collection\Client Tools on Collection.xml" -Force -ErrorAction SilentlyContinue
		Remove-Item "$ToolInstallPath\Default Menus\Collection\Console Tools on Collection.xml" -Force -ErrorAction SilentlyContinue
		Remove-Item "$ToolInstallPath\Default Menus\Deployment\Client Actions on Deployment.xml" -Force -ErrorAction SilentlyContinue
		Remove-Item "$ToolInstallPath\Default Menus\Deployment\Client Tools on Deployment.xml" -Force -ErrorAction SilentlyContinue
		Remove-Item "$ToolInstallPath\Default Menus\Deployment\Console Tools on Deployment.xml" -Force -ErrorAction SilentlyContinue
		Remove-Item "$ToolInstallPath\Default Menus\User\User Extensions.xml" -Force -ErrorAction SilentlyContinue
		Remove-Item "$ToolInstallPath\Default Menus\Application\Application Extensions.xml" -Force -ErrorAction SilentlyContinue
		Remove-Item "$ToolInstallPath\Default Menus\Package\Package Extensions.xml" -Force -ErrorAction SilentlyContinue
		Remove-Item "$ToolInstallPath\Default Menus\Boot Image\Boot Image Extensions.xml" -Force -ErrorAction SilentlyContinue
		Remove-Item "$ToolInstallPath\Default Menus\Driver Package\Driver Package Extensions.xml" -Force -ErrorAction SilentlyContinue
		Remove-Item "$ToolInstallPath\Default Menus\OS Install Package\OS Install Package Extensions.xml" -Force -ErrorAction SilentlyContinue
		Remove-Item "$ToolInstallPath\Default Menus\Software Update Package\Software Update Package Extensions.xml" -Force -ErrorAction SilentlyContinue
		Remove-Item "$ToolInstallPath\Default Menus\Image Package\Image Package Extensions.xml" -Force -ErrorAction SilentlyContinue

		New-Item "$XMLInstallPath\3fd01cd1-9e01-461e-92cd-94866b8d1f39" -Type Directory -ErrorAction SilentlyContinue
		New-Item "$XMLInstallPath\4f89279a-6f64-467a-8e04-f35cda1f50a4" -Type Directory -ErrorAction SilentlyContinue
		New-Item "$XMLInstallPath\8d4785b2-b055-43e2-afb1-a9347c95d971" -Type Directory -ErrorAction SilentlyContinue
		New-Item "$XMLInstallPath\93218e21-485a-4e2b-9f23-77c76145e214" -Type Directory -ErrorAction SilentlyContinue
		New-Item "$XMLInstallPath\0770186d-ea57-4276-a46b-7344ae081b58" -Type Directory -ErrorAction SilentlyContinue
		New-Item "$XMLInstallPath\3785759b-db2c-414e-a540-e879497c6f97" -Type Directory -ErrorAction SilentlyContinue
		New-Item "$XMLInstallPath\20313308-298b-4c29-9830-292c57dc83d3" -Type Directory -ErrorAction SilentlyContinue
		New-Item "$XMLInstallPath\21581552-82c3-42f7-b0bd-c48f04f2d148" -Type Directory -ErrorAction SilentlyContinue
		New-Item "$XMLInstallPath\a92615d6-9df3-49ba-a8c9-6ecb0e8b956b" -Type Directory -ErrorAction SilentlyContinue
		New-Item "$XMLInstallPath\d1621955-48ad-4bba-9c85-95f74c0c6538" -Type Directory -ErrorAction SilentlyContinue
		New-Item "$XMLInstallPath\ed9dee86-eadd-4ac8-82a1-7234a4646e62" -Type Directory -ErrorAction SilentlyContinue
		New-Item "$XMLInstallPath\f4739863-3c18-42c0-84cc-f214fe1be509" -Type Directory -ErrorAction SilentlyContinue
		New-Item "$XMLInstallPath\baaa6910-892f-4d20-9082-b392e5a28a53" -Type Directory -ErrorAction SilentlyContinue
		New-Item "$XMLInstallPath\a2560e1f-dd80-4280-8e8e-cbd9c6794ba7" -Type Directory -ErrorAction SilentlyContinue
		New-Item "$XMLInstallPath\968164ab-af86-459c-b89e-d3a49c05d367" -Type Directory -ErrorAction SilentlyContinue
		New-Item "$XMLInstallPath\9c69b0aa-a27c-43c9-8c26-5f964106a881" -Type Directory -ErrorAction SilentlyContinue
		New-Item "$XMLInstallPath\7a5f089c-ea90-4da2-aee9-d6d2673a861f" -Type Directory -ErrorAction SilentlyContinue
		New-Item "$XMLInstallPath\4b05362e-3ea4-4931-aa2d-3d889b1d75e4" -Type Directory -ErrorAction SilentlyContinue
		New-Item "$XMLInstallPath\7d0f75ec-3502-4b9d-b3ce-7b18b29942e8" -Type Directory -ErrorAction SilentlyContinue
		New-Item "$XMLInstallPath\606d3a81-6817-423c-bbe0-0c5c3e79c4ec" -Type Directory -ErrorAction SilentlyContinue
		New-Item "$XMLInstallPath\828a154e-4c7d-4d7f-ba6c-268443cdb4e8" -Type Directory -ErrorAction SilentlyContinue

		$ToolInstallPath = $ToolInstallPath.replace("`n","")
		$ToolInstallPath = $ToolInstallPath.replace("`t","")
		
		Get-Content "$Directory\Default Menus\Device\Client Actions on Device.xml" | ForEach-Object {
			$Line = $_
			$Line = $Line.Replace("C:\Program Files\SCCMConsoleExtensions","$ToolInstallPath")
			$Line >> "$ToolInstallPath\Default Menus\Device\Client Actions on Device.xml"
		}
		Copy-Item -Force "$ToolInstallPath\Default Menus\Device\Client Actions on Device.xml" "$XMLInstallPath\3fd01cd1-9e01-461e-92cd-94866b8d1f39"
		Copy-Item -Force "$ToolInstallPath\Default Menus\Device\Client Actions on Device.xml" "$XMLInstallPath\ed9dee86-eadd-4ac8-82a1-7234a4646e62"
		Copy-Item -Force "$ToolInstallPath\Default Menus\Device\Client Actions on Device.xml" "$XMLInstallPath\0770186d-ea57-4276-a46b-7344ae081b58"
		
		Get-Content "$Directory\Default Menus\Device\Client Tools on Device.xml" | ForEach-Object {
			$Line = $_
			$Line = $Line.Replace("C:\Program Files\SCCMConsoleExtensions","$ToolInstallPath")
			$Line >> "$ToolInstallPath\Default Menus\Device\Client Tools on Device.xml"
		}
		Copy-Item -Force "$ToolInstallPath\Default Menus\Device\Client Tools on Device.xml" "$XMLInstallPath\3fd01cd1-9e01-461e-92cd-94866b8d1f39"
		Copy-Item -Force "$ToolInstallPath\Default Menus\Device\Client Tools on Device.xml" "$XMLInstallPath\ed9dee86-eadd-4ac8-82a1-7234a4646e62"
		Copy-Item -Force "$ToolInstallPath\Default Menus\Device\Client Tools on Device.xml" "$XMLInstallPath\0770186d-ea57-4276-a46b-7344ae081b58"

		Get-Content "$Directory\Default Menus\Device\Console Tools on Device.xml" | ForEach-Object {
			$Line = $_
			$Line = $Line.Replace("C:\Program Files\SCCMConsoleExtensions","$ToolInstallPath")
			$Line >> "$ToolInstallPath\Default Menus\Device\Console Tools on Device.xml"
		}
		Copy-Item -Force "$ToolInstallPath\Default Menus\Device\Console Tools on Device.xml" "$XMLInstallPath\3fd01cd1-9e01-461e-92cd-94866b8d1f39\"
		Copy-Item -Force "$ToolInstallPath\Default Menus\Device\Console Tools on Device.xml" "$XMLInstallPath\ed9dee86-eadd-4ac8-82a1-7234a4646e62\"
		Copy-Item -Force "$ToolInstallPath\Default Menus\Device\Console Tools on Device.xml" "$XMLInstallPath\0770186d-ea57-4276-a46b-7344ae081b58\"
		
		Get-Content "$Directory\Default Menus\Collection\Client Actions on Collection.xml" | ForEach-Object {
			$Line = $_
			$Line = $Line.Replace("C:\Program Files\SCCMConsoleExtensions","$ToolInstallPath")
			$Line >> "$ToolInstallPath\Default Menus\Collection\Client Actions on Collection.xml"
		}
		Copy-Item -Force "$ToolInstallPath\Default Menus\Collection\Client Actions on Collection.xml" "$XMLInstallPath\3785759b-db2c-414e-a540-e879497c6f97"
		Copy-Item -Force "$ToolInstallPath\Default Menus\Collection\Client Actions on Collection.xml" "$XMLInstallPath\a92615d6-9df3-49ba-a8c9-6ecb0e8b956b"
		
		Get-Content "$Directory\Default Menus\Collection\Client Tools on Collection.xml" | ForEach-Object {
			$Line = $_
			$Line = $Line.Replace("C:\Program Files\SCCMConsoleExtensions","$ToolInstallPath")
			$Line >> "$ToolInstallPath\Default Menus\Collection\Client Tools on Collection.xml"
		}
		Copy-Item -Force "$ToolInstallPath\Default Menus\Collection\Client Tools on Collection.xml" "$XMLInstallPath\3785759b-db2c-414e-a540-e879497c6f97"
		Copy-Item -Force "$ToolInstallPath\Default Menus\Collection\Client Tools on Collection.xml" "$XMLInstallPath\a92615d6-9df3-49ba-a8c9-6ecb0e8b956b"
		
		Get-Content "$Directory\Default Menus\Collection\Console Tools on Collection.xml" | ForEach-Object {
			$Line = $_
			$Line = $Line.Replace("C:\Program Files\SCCMConsoleExtensions","$ToolInstallPath")
			$Line >> "$ToolInstallPath\Default Menus\Collection\Console Tools on Collection.xml"
		}
		Copy-Item -Force "$ToolInstallPath\Default Menus\Collection\Console Tools on Collection.xml" "$XMLInstallPath\3785759b-db2c-414e-a540-e879497c6f97"
		Copy-Item -Force "$ToolInstallPath\Default Menus\Collection\Console Tools on Collection.xml" "$XMLInstallPath\a92615d6-9df3-49ba-a8c9-6ecb0e8b956b"
		
		Get-Content "$Directory\Default Menus\Deployment\Client Actions on Deployment.xml" | ForEach-Object {
			$Line = $_
			$Line = $Line.Replace("C:\Program Files\SCCMConsoleExtensions","$ToolInstallPath")
			$Line >> "$ToolInstallPath\Default Menus\Deployment\Client Actions on Deployment.xml"
		}
		Copy-Item "$ToolInstallPath\Default Menus\Deployment\Client Actions on Deployment.xml" "$XMLInstallPath\4f89279a-6f64-467a-8e04-f35cda1f50a4" -force
		Copy-Item "$ToolInstallPath\Default Menus\Deployment\Client Actions on Deployment.xml" "$XMLInstallPath\8d4785b2-b055-43e2-afb1-a9347c95d971" -force
		Copy-Item "$ToolInstallPath\Default Menus\Deployment\Client Actions on Deployment.xml" "$XMLInstallPath\93218e21-485a-4e2b-9f23-77c76145e214" -force
		Copy-Item "$ToolInstallPath\Default Menus\Deployment\Client Actions on Deployment.xml" "$XMLInstallPath\20313308-298b-4c29-9830-292c57dc83d3" -force
		Copy-Item "$ToolInstallPath\Default Menus\Deployment\Client Actions on Deployment.xml" "$XMLInstallPath\21581552-82c3-42f7-b0bd-c48f04f2d148" -force
		Copy-Item "$ToolInstallPath\Default Menus\Deployment\Client Actions on Deployment.xml" "$XMLInstallPath\d1621955-48ad-4bba-9c85-95f74c0c6538" -force
		Copy-Item "$ToolInstallPath\Default Menus\Deployment\Client Actions on Deployment.xml" "$XMLInstallPath\f4739863-3c18-42c0-84cc-f214fe1be509" -force
		
		Get-Content "$Directory\Default Menus\Deployment\Client Tools on Deployment.xml" | ForEach-Object {
			$Line = $_
			$Line = $Line.Replace("C:\Program Files\SCCMConsoleExtensions","$ToolInstallPath")
			$Line >> "$ToolInstallPath\Default Menus\Deployment\Client Tools on Deployment.xml"
		}
		Copy-Item "$ToolInstallPath\Default Menus\Deployment\Client Tools on Deployment.xml" "$XMLInstallPath\4f89279a-6f64-467a-8e04-f35cda1f50a4" -force
		Copy-Item "$ToolInstallPath\Default Menus\Deployment\Client Tools on Deployment.xml" "$XMLInstallPath\8d4785b2-b055-43e2-afb1-a9347c95d971" -force
		Copy-Item "$ToolInstallPath\Default Menus\Deployment\Client Tools on Deployment.xml" "$XMLInstallPath\93218e21-485a-4e2b-9f23-77c76145e214" -force
		Copy-Item "$ToolInstallPath\Default Menus\Deployment\Client Tools on Deployment.xml" "$XMLInstallPath\20313308-298b-4c29-9830-292c57dc83d3" -force
		Copy-Item "$ToolInstallPath\Default Menus\Deployment\Client Tools on Deployment.xml" "$XMLInstallPath\21581552-82c3-42f7-b0bd-c48f04f2d148" -force
		Copy-Item "$ToolInstallPath\Default Menus\Deployment\Client Tools on Deployment.xml" "$XMLInstallPath\d1621955-48ad-4bba-9c85-95f74c0c6538" -force
		Copy-Item "$ToolInstallPath\Default Menus\Deployment\Client Tools on Deployment.xml" "$XMLInstallPath\f4739863-3c18-42c0-84cc-f214fe1be509" -force
		
		Get-Content "$Directory\Default Menus\Deployment\Console Tools on Deployment.xml" | ForEach-Object {
			$Line = $_
			$Line = $Line.Replace("C:\Program Files\SCCMConsoleExtensions","$ToolInstallPath")
			$Line >> "$ToolInstallPath\Default Menus\Deployment\Console Tools on Deployment.xml"
		}
		Copy-Item "$ToolInstallPath\Default Menus\Deployment\Console Tools on Deployment.xml" "$XMLInstallPath\4f89279a-6f64-467a-8e04-f35cda1f50a4" -force
		Copy-Item "$ToolInstallPath\Default Menus\Deployment\Console Tools on Deployment.xml" "$XMLInstallPath\8d4785b2-b055-43e2-afb1-a9347c95d971" -force
		Copy-Item "$ToolInstallPath\Default Menus\Deployment\Console Tools on Deployment.xml" "$XMLInstallPath\93218e21-485a-4e2b-9f23-77c76145e214" -force
		Copy-Item "$ToolInstallPath\Default Menus\Deployment\Console Tools on Deployment.xml" "$XMLInstallPath\20313308-298b-4c29-9830-292c57dc83d3" -force
		Copy-Item "$ToolInstallPath\Default Menus\Deployment\Console Tools on Deployment.xml" "$XMLInstallPath\21581552-82c3-42f7-b0bd-c48f04f2d148" -force
		Copy-Item "$ToolInstallPath\Default Menus\Deployment\Console Tools on Deployment.xml" "$XMLInstallPath\d1621955-48ad-4bba-9c85-95f74c0c6538" -force
		Copy-Item "$ToolInstallPath\Default Menus\Deployment\Console Tools on Deployment.xml" "$XMLInstallPath\f4739863-3c18-42c0-84cc-f214fe1be509" -force
		
		Get-Content "$Directory\Default Menus\User\User Extensions.xml" | ForEach-Object {
			$Line = $_
			$Line = $Line.Replace("C:\Program Files\SCCMConsoleExtensions","$ToolInstallPath")
			$Line >> "$ToolInstallPath\Default Menus\User\User Extensions.xml"
		}
		Copy-Item "$ToolInstallPath\Default Menus\User\User Extensions.xml" "$XMLInstallPath\baaa6910-892f-4d20-9082-b392e5a28a53" -force
		Copy-Item "$ToolInstallPath\Default Menus\User\User Extensions.xml" "$XMLInstallPath\a2560e1f-dd80-4280-8e8e-cbd9c6794ba7" -force
		
		Get-Content "$Directory\Default Menus\Application\Application Extensions.xml" | ForEach-Object {
			$Line = $_
			$Line = $Line.Replace("C:\Program Files\SCCMConsoleExtensions","$ToolInstallPath")
			$Line >> "$ToolInstallPath\Default Menus\Application\Application Extensions.xml"
		}
		Copy-Item "$ToolInstallPath\Default Menus\Application\Application Extensions.xml" "$XMLInstallPath\968164ab-af86-459c-b89e-d3a49c05d367" -force
			
		Get-Content "$Directory\Default Menus\Package\Package Extensions.xml" | ForEach-Object {
			$Line = $_
			$Line = $Line.Replace("C:\Program Files\SCCMConsoleExtensions","$ToolInstallPath")
			$Line >> "$ToolInstallPath\Default Menus\Package\Package Extensions.xml"
		}
		Copy-Item "$ToolInstallPath\Default Menus\Package\Package Extensions.xml" "$XMLInstallPath\9c69b0aa-a27c-43c9-8c26-5f964106a881" -force			
		
		Get-Content "$Directory\Default Menus\Boot Image\Boot Image Extensions.xml" | ForEach-Object {
			$Line = $_
			$Line = $Line.Replace("C:\Program Files\SCCMConsoleExtensions","$ToolInstallPath")
			$Line >> "$ToolInstallPath\Default Menus\Boot Image\Boot Image Extensions.xml"
		}
		Copy-Item "$ToolInstallPath\Default Menus\Boot Image\Boot Image Extensions.xml" "$XMLInstallPath\7a5f089c-ea90-4da2-aee9-d6d2673a861f" -force			
		
		Get-Content "$Directory\Default Menus\Driver Package\Driver Package Extensions.xml" | ForEach-Object {
			$Line = $_
			$Line = $Line.Replace("C:\Program Files\SCCMConsoleExtensions","$ToolInstallPath")
			$Line >> "$ToolInstallPath\Default Menus\Driver Package\Driver Package Extensions.xml"
		}
		Copy-Item "$ToolInstallPath\Default Menus\Driver Package\Driver Package Extensions.xml" "$XMLInstallPath\4b05362e-3ea4-4931-aa2d-3d889b1d75e4" -force			
		
		Get-Content "$Directory\Default Menus\OS Install Package\OS Install Package Extensions.xml" | ForEach-Object {
			$Line = $_
			$Line = $Line.Replace("C:\Program Files\SCCMConsoleExtensions","$ToolInstallPath")
			$Line >> "$ToolInstallPath\Default Menus\OS Install Package\OS Install Package Extensions.xml"
		}
		Copy-Item "$ToolInstallPath\Default Menus\OS Install Package\OS Install Package Extensions.xml" "$XMLInstallPath\7d0f75ec-3502-4b9d-b3ce-7b18b29942e8" -force			

		Get-Content "$Directory\Default Menus\Software Update Package\Software Update Package Extensions.xml" | ForEach-Object {
			$Line = $_
			$Line = $Line.Replace("C:\Program Files\SCCMConsoleExtensions","$ToolInstallPath")
			$Line >> "$ToolInstallPath\Default Menus\Software Update Package\Software Update Package Extensions.xml"
		}
		Copy-Item "$ToolInstallPath\Default Menus\Software Update Package\Software Update Package Extensions.xml" "$XMLInstallPath\606d3a81-6817-423c-bbe0-0c5c3e79c4ec" -force			

		Get-Content "$Directory\Default Menus\Image Package\Image Package Extensions.xml" | ForEach-Object {
			$Line = $_
			$Line = $Line.Replace("C:\Program Files\SCCMConsoleExtensions","$ToolInstallPath")
			$Line >> "$ToolInstallPath\Default Menus\Image Package\Image Package Extensions.xml"
		}
		Copy-Item "$ToolInstallPath\Default Menus\Image Package\Image Package Extensions.xml" "$XMLInstallPath\828a154e-4c7d-4d7f-ba6c-268443cdb4e8" -force			
		
		"Version=$Version" > "$ToolInstallPath\Install Properties.ini"
		"XMLPath=$XMLInstallPath" >> "$ToolInstallPath\Install Properties.ini"
		"ToolPath=$ToolInstallPath" >> "$ToolInstallPath\Install Properties.ini"
		
		$Popup.popup("Finished installing!  Please close and re-open the ConfigMgr Console to see the new tools!",0,”Done”,0)
		$InstallForm.close()
	}
	}
	Else {$Popup.popup("Could not locate ConfigMgr Install Location",0,”Error”,16)}
}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$InstallForm.WindowState = $InitialFormWindowState
	$ConfigInstallPath = $env:SMS_ADMIN_UI_PATH | Out-String
	$ConfigInstallPath = $ConfigInstallPath -replace "\\bin\\i386", ""
	$ConfigMgrInstallLocBox.Text = $ConfigInstallPath
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 237
$System_Drawing_Size.Width = 544
$InstallForm.ClientSize = $System_Drawing_Size
$InstallForm.ControlBox = $False
$InstallForm.DataBindings.DefaultDataSourceUpdateMode = 0
$InstallForm.FormBorderStyle = 1
$InstallForm.Name = "InstallForm"
$InstallForm.Text = "Powershell Right Click Tools Installer"


$RemoveOldToolsBox.Checked = $True
$RemoveOldToolsBox.CheckState = 1
$RemoveOldToolsBox.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 196
$System_Drawing_Point.Y = 171
$RemoveOldToolsBox.Location = $System_Drawing_Point
$RemoveOldToolsBox.Name = "RemoveOldToolsBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 226
$RemoveOldToolsBox.Size = $System_Drawing_Size
$RemoveOldToolsBox.TabIndex = 10
$RemoveOldToolsBox.Text = "Remove Old Tools"
$RemoveOldToolsBox.UseVisualStyleBackColor = $True

$InstallForm.Controls.Add($RemoveOldToolsBox)


$ConfigInstallBrowse.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 457
$System_Drawing_Point.Y = 130
$ConfigInstallBrowse.Location = $System_Drawing_Point
$ConfigInstallBrowse.Name = "ConfigInstallBrowse"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$ConfigInstallBrowse.Size = $System_Drawing_Size
$ConfigInstallBrowse.TabIndex = 9
$ConfigInstallBrowse.Text = "Browse"
$ConfigInstallBrowse.UseVisualStyleBackColor = $True
$ConfigInstallBrowse.add_Click($Config_Browse)
$ConfigInstallBrowse.add_KeyPress($Config_Browse)

$InstallForm.Controls.Add($ConfigInstallBrowse)

$ConfigMgrInstallLocBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 130
$ConfigMgrInstallLocBox.Location = $System_Drawing_Point
$ConfigMgrInstallLocBox.Name = "ConfigMgrInstallLocBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 439
$ConfigMgrInstallLocBox.Size = $System_Drawing_Size
$ConfigMgrInstallLocBox.TabIndex = 8

$InstallForm.Controls.Add($ConfigMgrInstallLocBox)

$ConfigMgrLbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 104
$ConfigMgrLbl.Location = $System_Drawing_Point
$ConfigMgrLbl.Name = "ConfigMgrLbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 382
$ConfigMgrLbl.Size = $System_Drawing_Size
$ConfigMgrLbl.TabIndex = 7
$ConfigMgrLbl.Text = "ConfigMgr 2012 Install Location:"
$ConfigMgrLbl.TextAlign = 16

$InstallForm.Controls.Add($ConfigMgrLbl)


$InstallToBrowse.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 457
$System_Drawing_Point.Y = 68
$InstallToBrowse.Location = $System_Drawing_Point
$InstallToBrowse.Name = "InstallToBrowse"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$InstallToBrowse.Size = $System_Drawing_Size
$InstallToBrowse.TabIndex = 6
$InstallToBrowse.Text = "Browse"
$InstallToBrowse.UseVisualStyleBackColor = $True
$InstallToBrowse.add_Click($Install_Browse)
$InstallToBrowse.add_KeyPress($Install_Browse)

$InstallForm.Controls.Add($InstallToBrowse)

$InstallToBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 68
$InstallToBox.Location = $System_Drawing_Point
$InstallToBox.Name = "InstallToBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 439
$InstallToBox.Size = $System_Drawing_Size
$InstallToBox.TabIndex = 5
$InstallToBox.Text = "C:\Program Files\SCCMConsoleExtensions"

$InstallForm.Controls.Add($InstallToBox)

$InstallToLbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 42
$InstallToLbl.Location = $System_Drawing_Point
$InstallToLbl.Name = "InstallToLbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 291
$InstallToLbl.Size = $System_Drawing_Size
$InstallToLbl.TabIndex = 4
$InstallToLbl.Text = "Install Tools To:"
$InstallToLbl.TextAlign = 16

$InstallForm.Controls.Add($InstallToLbl)

$PSToolsLbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 9
$PSToolsLbl.Location = $System_Drawing_Point
$PSToolsLbl.Name = "PSToolsLbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 520
$PSToolsLbl.Size = $System_Drawing_Size
$PSToolsLbl.TabIndex = 3
$PSToolsLbl.Text = "Powershell Right Click Tools"
$PSToolsLbl.TextAlign = 32

$InstallForm.Controls.Add($PSToolsLbl)


$CancelBtn.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 196
$CancelBtn.Location = $System_Drawing_Point
$CancelBtn.Name = "CancelBtn"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$CancelBtn.Size = $System_Drawing_Size
$CancelBtn.TabIndex = 1
$CancelBtn.Text = "Cancel"
$CancelBtn.UseVisualStyleBackColor = $True
$CancelBtn.add_Click($Cancel_Btn)
$CancelBtn.add_KeyPress($Cancel_Btn)

$InstallForm.Controls.Add($CancelBtn)


$NextBtn.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 457
$System_Drawing_Point.Y = 202
$NextBtn.Location = $System_Drawing_Point
$NextBtn.Name = "NextBtn"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$NextBtn.Size = $System_Drawing_Size
$NextBtn.TabIndex = 0
$NextBtn.Text = "Install"
$NextBtn.UseVisualStyleBackColor = $True
$NextBtn.add_Click($Install_Btn)
$NextBtn.add_KeyPress($Install_Btn)

$InstallForm.Controls.Add($NextBtn)

$openFileDialog1.FileName = "openFileDialog1"
$openFileDialog1.ShowHelp = $True

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $InstallForm.WindowState
#Init the OnLoad event to correct the initial state of the form
$InstallForm.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$InstallForm.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
