#COLOR=Yellow
#Requires -Version 1
# This is a sophisticated script.  Notice the following:
#  - It supports error TRAPPING
#  - It uses VERBOSE stream
#  - It is digitally signed
#
#COLOR=

function Get-Total(
   [String]$property      = $(throw "Property Name Required"),
   [ScriptBlock]$filter   = {$true}
)
{
   Begin
   {   $total = 0
   }

   Process
   {   if ($_ |where $filter)
       {   $total += $_.$property 
       }else
#COLOR=RED
       {  Write-Verbose "Skipping $_"
#COLOR=
       }
   }


   End
   {   "Total $property = $total"
   }
}


#COLOR=Yellow
############ RUN IT #########################
#COLOR=RED
trap [System.Management.Automation.RuntimeException] {
        "`nContinuing after an runtime error`n"
        continue
}
#COLOR=
$VerbosePreference="Continue"
Get-Process | Get-Total 
Get-Process | Get-Total -Property Handles  -filter {$_.company -match "Microsoft"}

#COLOR=RED
# SIG # Begin signature block
# MIIPlgYJKoZIhvcNAQcCoIIPhzCCD4MCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUwYBRNAQvhsAx2XOH/O2B4Q0/
# jcaggg2wMIIEEzCCA0CgAwIBAgIQaguZT8AAIqsR2wJCfALTvjAJBgUrDgMCHQUA
# MHUxKzApBgNVBAsTIkNvcHlyaWdodCAoYykgMTk5OSBNaWNyb3NvZnQgQ29ycC4x
# HjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9z
# b2Z0IFRlc3QgUm9vdCBBdXRob3JpdHkwHhcNMDYwNjIyMjI1NzMxWhcNMTEwNjIx
# MDcwMDAwWjBxMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4G
# A1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMRsw
# GQYDVQQDExJNaWNyb3NvZnQgVGVzdCBQQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
# DwAwggEKAoIBAQCP8/PfeqdyKGF+kPOBZ088QoCzw3JN738QZbhK18ZNrGebr6P9
# xO18NGxVc15xCRygojr1ZVPU3M/zM6NaMyxXzUght6UkMDFTNana2dt0f0wueGfN
# 28ntsY+3rv95b6wjBlQOI0M3eN0+Tgpt0Cr2xn5bknQNsxMPXLFxtBD8sSAICC55
# bl/ScjSukjqBsDKszkNZMKbB/K74zOh9hmtcruvelfoqOXUGXEE6UdxXNU6Syyyd
# e6Tcmun+IZxhHzukTH9SsYU5ZH2RiW+eFEKzvKLaaheHJOYb1Xx9j6rcAsmhXt39
# gSqfJsM2QdPP/HMNHHQoOPKlCsXRD7vTvtCTAgMBAAGjgeswgegwgagGA1UdAQSB
# oDCBnYAQwGNF16MBfXnFenpfKNtD1qF3MHUxKzApBgNVBAsTIkNvcHlyaWdodCAo
# YykgMTk5OSBNaWNyb3NvZnQgQ29ycC4xHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jw
# b3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRlc3QgUm9vdCBBdXRob3JpdHmC
# EF/qT9LyHUMQtuhUPtiVJhgwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUVKUh
# TKCub5xgTg/O3UbV12HWF6wwCwYDVR0PBAQDAgGGMAkGBSsOAwIdBQADgcEALM4P
# BbDuH2UZ4qMnvJz3fqMlqt0sx+vFAoExl8lNv0xYMMgn1aeIzp6lDu+ZNYz1Dhws
# zLaQwaB1zeZ99AsRMXqD+/5oTMUbm1SqKeArXbkkU/nswZwlgyVAY7cpQhx508Lx
# zKP6hjCLq1tKkMtEIJDswAVLXmvgOfGfvzelnmdJeHWj42tLPmZsa6wMiPS6McEK
# puUj3r5GTuhVDYMjehCRKYZB/4GuZFegl8Hdi5dcVz4Xzxt4sdIXRLygmE+PMIIE
# bzCCA1egAwIBAgIKYTCS4AAAAAAABDANBgkqhkiG9w0BAQUFADBxMQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMRswGQYDVQQDExJNaWNyb3NvZnQg
# VGVzdCBQQ0EwHhcNMDYwNjIyMjMyNjU0WhcNMDcxMjIyMjMzNjU0WjAiMSAwHgYD
# VQQDExdNaWNyb3NvZnQgV2luZG93cyBOVERFVjCCASIwDQYJKoZIhvcNAQEBBQAD
# ggEPADCCAQoCggEBAOOXyvQiNAy4GVTDdmvD95yNw+nhOKd7/C6YmnnANKOfxL7V
# PzLKe/y6lmJlFQ4GxqZ+DlQ/OUZTuB5wOdBGitdgT+ihsVDbsSvjnYnfyX8gnpcV
# /Xp9V/btnnbCMd0NvmZ0GE/3Y3dxgwqCS34rFNJnR3tYP+sw30cv+Yk08FmuSvll
# TKaTgx7SotsrvHL/qY8+CKXLLNz326EWhrn58MoswD1YZEzbVhYUUr2l+VKxm1tK
# VirEZdTddYZfupyuFsI2VsRiMsHJOYJHJYwF4m1Zv0MHHy5C13rjw5ycdcG9k7na
# EOAQ5C+yPvWFm4Qth4HbO5aznjvwAefKi0NkfCUCAwEAAaOCAVYwggFSMA8GA1Ud
# EwEB/wQFMAMBAf8wHQYDVR0OBBYEFMqHsCxPDvXXO5j6UAT6XtUDIlXGMAsGA1Ud
# DwQEAwIBhjASBgkrBgEEAYI3FQEEBQIDAgACMCMGCSsGAQQBgjcVAgQWBBQuvxjk
# Ycz28VNko7OLRenqkWcaqTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTAfBgNV
# HSMEGDAWgBRUpSFMoK5vnGBOD87dRtXXYdYXrDBMBgNVHR8ERTBDMEGgP6A9hjto
# dHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9sZWdhY3l0
# ZXN0cGNhLmNybDBQBggrBgEFBQcBAQREMEIwQAYIKwYBBQUHMAKGNGh0dHA6Ly93
# d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMvTGVnYWN5VGVzdFBDQS5jcnQwDQYJ
# KoZIhvcNAQEFBQADggEBABFhEQOUdeQNPzmc1NfRMtUhpcmCkSsNNTlJQMckdMG/
# liq99zWk/rfJKK5v/K5+sjV534T153PY1Ag2YYyvway1p9v67Bx02TmzKlypwjuD
# zplscXj195ZqvLd3DJXg3zjZEXaSeaMr94w7CuLcLCvc24HJBB6r5h12TvVLR9jO
# XMla+6WKb+eWcEnRC1fCrAU8TI3JrRG0wNvlAsgydCM2dw4zNgPCYsAp2fpM0MIm
# WwJYvlHcn/tWs9+lMA7MafqRJNwgqNl17wHjA+v72FVGkkFgQ9AsxAl3SDpkN3j2
# TZrUQN5Ni58k0EqXSUo8spOkxmchQ2Goite730s42n4wggUiMIIECqADAgECAgof
# CdihAAIAAisPMA0GCSqGSIb3DQEBBQUAMCIxIDAeBgNVBAMTF01pY3Jvc29mdCBX
# aW5kb3dzIE5UREVWMB4XDTA3MDcxNjE5NTk0M1oXDTA3MTIyMjIzMzY1NFowGTEX
# MBUGA1UEAxMOSmVmZnJleSBTbm92ZXIwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJ
# AoGBALy4bsVqqD/OiJKpPixFArPHDkmqZ1kHF/cxoCPDHnKFpmy+JmKoz3NESa2Q
# g95QQE4HPeo069W2TUTcBbhxkA1H8x/9+uxiS9sn49qoxwhFcUO01r5BrzuI4xzx
# SOkxxJ0cU2Zrwat4o3cmtL7PNhiHKWaeV8QAU2buUQOmO+OVAgMBAAGjggLlMIIC
# 4TA9BgkrBgEEAYI3FQcEMDAuBiYrBgEEAYI3FQiGuYgUhvKOIYedlRyF94Jk16Zv
# gXqB++9hhtbaGQIBZAIBBzAfBgNVHSUEGDAWBggrBgEFBQcDAwYKKwYBBAGCNwoD
# BjALBgNVHQ8EBAMCB4AwKQYJKwYBBAGCNxUKBBwwGjAKBggrBgEFBQcDAzAMBgor
# BgEEAYI3CgMGMB0GA1UdDgQWBBT20/OcsfRFz145rK4zmWuvGUigwTAfBgNVHSME
# GDAWgBTKh7AsTw711zuY+lAE+l7VAyJVxjCCAScGA1UdHwSCAR4wggEaMIIBFqCC
# ARKgggEOhoHUbGRhcDovLy9DTj1NaWNyb3NvZnQlMjBXaW5kb3dzJTIwTlRERVYo
# MiksQ049Q1JMLENOPUNEUCxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNlcyxDTj1T
# ZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPW50ZGV2LERDPWNvcnAsREM9bWlj
# cm9zb2Z0LERDPWNvbT9jZXJ0aWZpY2F0ZVJldm9jYXRpb25MaXN0P2Jhc2U/b2Jq
# ZWN0Q2xhc3M9Y1JMRGlzdHJpYnV0aW9uUG9pbnSGNWh0dHA6Ly9jb3JwcGtpL2Ny
# bC9NaWNyb3NvZnQlMjBXaW5kb3dzJTIwTlRERVYoMikuY3JsMIGjBggrBgEFBQcB
# AQSBljCBkzBOBggrBgEFBQcwAoZCaHR0cDovL250ZGV2aXRnY2FiMDQvQ2VydEVu
# cm9sbC9NaWNyb3NvZnQlMjBXaW5kb3dzJTIwTlRERVYoMikuY3J0MEEGCCsGAQUF
# BzAChjVodHRwOi8vY29ycHBraS9haWEvTWljcm9zb2Z0JTIwV2luZG93cyUyME5U
# REVWKDIpLmNydDA2BgNVHREELzAtoCsGCisGAQQBgjcUAgOgHQwbanNub3ZlckBu
# dGRldi5taWNyb3NvZnQuY29tMA0GCSqGSIb3DQEBBQUAA4IBAQCsctjYIEyLYgMc
# H6jGSD+wZxgxqR6jtyJQVzq9rry4uAFoWjVnOMThkKCxQrBpJyREiIUP9cUDyPZg
# 5Bx4Y1tLL7WF/WRatqgzYuCh7WWwyVFo2zh7WEw74iBT4J2tVWGF3uUlFPt3m4mq
# UQkeVihaa2R1ILQOxEofrme3f7entAlAhYp8gjzWhpST6CaCvyvNOpMr7n7DheAj
# iwSMMUzX5b7Wzf8ljb9Grq5ZOEONfu66Lh4NRoj5mVyxiRjjZaxGbEVdGvaH+diV
# 2+LGoffhnLeqh7u1p+VyOk706OcyF3sfW5S4L++lEgwYvDHbBjEQmxd1akFglE4x
# XEo1ajzKMYIBUDCCAUwCAQEwMDAiMSAwHgYDVQQDExdNaWNyb3NvZnQgV2luZG93
# cyBOVERFVgIKHwnYoQACAAIrDzAJBgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEK
# MAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3
# AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQUrEQxZ04WO3Af9bGX
# VID3zzX2VdcwDQYJKoZIhvcNAQEBBQAEgYCL2M6EOocY70huId/YDDVA1Ns2QYnS
# kk+o1JpSX5HADlpwFxKefZFFAiItjoRi8gOkDUNKfTb7JFf+Fr2Sn7815KtlIMCt
# Rtgk/pjgg//IEVr2A4YHp6UA59k6B7DIz1iv5n6uyiVLjsW5tCOpZbhkVSWLmFWb
# TkRJZk9+gAo0bQ==
# SIG # End signature block
